# Generated by Django 5.2.17 on 2026-08-31 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chiffrage", "0001_initial"),
        ("commercial", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvoiSousTraitance",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_envoi", models.DateField(default=django.utils.timezone.now)),
                ("quantite_envoyee", models.FloatField()),
                ("statut", models.CharField(blank=True, max_length=50)),
                (
                    "operation_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envois_sous_traitance",
                        to="chiffrage.operationof",
                    ),
                ),
                (
                    "sous_traitant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envois_sous_traitance",
                        to="commercial.tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envoi en sous-traitance",
                "verbose_name_plural": "Envois en sous-traitance",
                "ordering": ["-date_envoi", "numero"],
            },
        ),
        migrations.CreateModel(
            name="RetourSousTraitance",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_retour", models.DateField(default=django.utils.timezone.now)),
                ("quantite_retournee", models.FloatField()),
                (
                    "conforme",
                    models.BooleanField(
                        default=True, help_text="Contrôle qualité simple"
                    ),
                ),
                (
                    "envoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retours",
                        to="soustraitance.envoisoustraitance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour de sous-traitance",
                "verbose_name_plural": "Retours de sous-traitance",
                "ordering": ["-date_retour", "numero"],
            },
        ),
    ]
