# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0002_alter_commande_adresse_facturation_and_more"),
        ("commercial", "0003_alter_adresse_adresse_alter_adresse_code_postal_and_more"),
        ("soustraitance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="date_envoi",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date d'envoi"
            ),
        ),
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="operation_of",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="envois_sous_traitance",
                to="chiffrage.operationof",
                verbose_name="opération d'ordre de fabrication",
            ),
        ),
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="quantite_envoyee",
            field=models.FloatField(verbose_name="quantité envoyée"),
        ),
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="sous_traitant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="envois_sous_traitance",
                to="commercial.tiers",
                verbose_name="sous-traitant",
            ),
        ),
        migrations.AlterField(
            model_name="envoisoustraitance",
            name="statut",
            field=models.CharField(blank=True, max_length=50, verbose_name="statut"),
        ),
        migrations.AlterField(
            model_name="retoursoustraitance",
            name="conforme",
            field=models.BooleanField(
                default=True,
                help_text="Contrôle qualité simple",
                verbose_name="conforme",
            ),
        ),
        migrations.AlterField(
            model_name="retoursoustraitance",
            name="date_retour",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date de retour"
            ),
        ),
        migrations.AlterField(
            model_name="retoursoustraitance",
            name="envoi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retours",
                to="soustraitance.envoisoustraitance",
                verbose_name="envoi",
            ),
        ),
        migrations.AlterField(
            model_name="retoursoustraitance",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="retoursoustraitance",
            name="quantite_retournee",
            field=models.FloatField(verbose_name="quantité retournée"),
        ),
    ]
