# Generated by Django 5.2.17 on 2026-08-31 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emplacement",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("libelle", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Emplacement",
                "verbose_name_plural": "Emplacements",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.FloatField(default=0)),
                (
                    "longueur_restante",
                    models.FloatField(
                        blank=True, help_text="Inutilisé en v1", null=True
                    ),
                ),
                ("statut", models.CharField(blank=True, max_length=50)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="technique.article",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="stock.emplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "ordering": ["article", "emplacement"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=20,
                    ),
                ),
                ("quantite", models.FloatField()),
                ("date_mouvement", models.DateField(default=django.utils.timezone.now)),
                (
                    "reference_origine",
                    models.CharField(
                        blank=True,
                        help_text="Pointe vers l'OF, la commande fournisseur, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="stock.lot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date_mouvement", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AlerteStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_declenchement",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("active", "Active"), ("traitee", "Traitée")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "date_traitement",
                    models.DateField(
                        blank=True,
                        help_text="Clôture auto (stock remonté) ou manuelle (commande fournisseur)",
                        null=True,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_stock",
                        to="technique.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de stock",
                "verbose_name_plural": "Alertes de stock",
                "ordering": ["-date_declenchement"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("statut", "active")),
                        fields=("article",),
                        name="une_seule_alerte_active_par_article",
                    )
                ],
            },
        ),
    ]
