# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
        (
            "technique",
            "0002_alter_article_cout_unitaire_alter_article_epaisseur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertestock",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertes_stock",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="alertestock",
            name="date_declenchement",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date de déclenchement"
            ),
        ),
        migrations.AlterField(
            model_name="alertestock",
            name="date_traitement",
            field=models.DateField(
                blank=True,
                help_text="Clôture auto (stock remonté) ou manuelle (commande fournisseur)",
                null=True,
                verbose_name="date de traitement",
            ),
        ),
        migrations.AlterField(
            model_name="alertestock",
            name="statut",
            field=models.CharField(
                choices=[("active", "Active"), ("traitee", "Traitée")],
                default="active",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="emplacement",
            name="code",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="emplacement",
            name="libelle",
            field=models.CharField(blank=True, max_length=200, verbose_name="libellé"),
        ),
        migrations.AlterField(
            model_name="lot",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="emplacement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="stock.emplacement",
                verbose_name="emplacement",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="longueur_restante",
            field=models.FloatField(
                blank=True,
                help_text="Inutilisé en v1",
                null=True,
                verbose_name="longueur restante",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="quantite",
            field=models.FloatField(default=0, verbose_name="quantité"),
        ),
        migrations.AlterField(
            model_name="lot",
            name="statut",
            field=models.CharField(blank=True, max_length=50, verbose_name="statut"),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="date_mouvement",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date de mouvement"
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouvements",
                to="stock.lot",
                verbose_name="lot",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="quantite",
            field=models.FloatField(verbose_name="quantité"),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="reference_origine",
            field=models.CharField(
                blank=True,
                help_text="Pointe vers l'OF, la commande fournisseur, etc.",
                max_length=100,
                verbose_name="référence d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="type_mouvement",
            field=models.CharField(
                choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                max_length=20,
                verbose_name="type de mouvement",
            ),
        ),
    ]
