# Generated by Django 5.2.17 on 2026-10-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_alertestock_article_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mouvementstock",
            options={
                "ordering": ["-date_mouvement", "-id"],
                "permissions": [
                    (
                        "annuler_mouvement",
                        "Peut annuler (contre-passer) un mouvement de stock",
                    )
                ],
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
            },
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="annule_mouvement",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="Renseigné sur un mouvement de contre-passation : pointe vers l'original qu'il annule.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contre_passation",
                to="stock.mouvementstock",
                verbose_name="mouvement annulé",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="enregistré le"
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="motif",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire pour un mouvement saisi à la main (sans référence d'origine).",
                max_length=200,
                verbose_name="motif",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_stock",
                to=settings.AUTH_USER_MODEL,
                verbose_name="saisi par",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="date_mouvement",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="date de mouvement",
            ),
        ),
    ]
