# Generated by Django 5.2.17 on 2026-10-02 21:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_mouvements_immuables"),
        ("technique", "0005_article_taux_tva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="cout_unitaire_moyen",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="Recalculé à chaque entrée valorisée (réception, transfert) ; inchangé par les sorties.",
                verbose_name="coût unitaire moyen pondéré",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="cout_unitaire",
            field=models.FloatField(
                blank=True,
                help_text="Valorisation d'une entrée (prix d'achat, coût de transfert) ; sert au coût moyen pondéré du lot.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="coût unitaire",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEmplacement",
            fields=[
                (
                    "code",
                    models.CharField(db_index=True, max_length=50, verbose_name="code"),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="libellé"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Emplacement",
                "verbose_name_plural": "historical Emplacements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLot",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("quantite", models.FloatField(default=0, verbose_name="quantité")),
                (
                    "longueur_restante",
                    models.FloatField(
                        blank=True,
                        help_text="Inutilisé en v1",
                        null=True,
                        verbose_name="longueur restante",
                    ),
                ),
                (
                    "statut",
                    models.CharField(blank=True, max_length=50, verbose_name="statut"),
                ),
                (
                    "cout_unitaire_moyen",
                    models.FloatField(
                        default=0,
                        editable=False,
                        help_text="Recalculé à chaque entrée valorisée (réception, transfert) ; inchangé par les sorties.",
                        verbose_name="coût unitaire moyen pondéré",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stock.emplacement",
                        verbose_name="emplacement",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lot",
                "verbose_name_plural": "historical Lots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_inventaire",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date du comptage",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="commentaire"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                        default="brouillon",
                        editable=False,
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="validé le"
                    ),
                ),
                (
                    "utilisateur_validation",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventaires_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventaire",
                "verbose_name_plural": "Inventaires",
                "ordering": ["-date_inventaire", "-id"],
                "permissions": [
                    (
                        "valider_inventaire",
                        "Peut valider un inventaire (ajuste le stock)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "date_transfert",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date du transfert",
                    ),
                ),
                (
                    "motif",
                    models.CharField(blank=True, max_length=200, verbose_name="motif"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="enregistré le"
                    ),
                ),
                (
                    "emplacement_cible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_entrants",
                        to="stock.emplacement",
                        verbose_name="emplacement cible",
                    ),
                ),
                (
                    "lot_cible",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_entrants",
                        to="stock.lot",
                        verbose_name="lot cible",
                    ),
                ),
                (
                    "lot_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_sortants",
                        to="stock.lot",
                        verbose_name="lot source",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts_stock",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="saisi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de stock",
                "verbose_name_plural": "Transferts de stock",
                "ordering": ["-date_transfert", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InventaireLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_comptee",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="quantité comptée",
                    ),
                ),
                (
                    "quantite_theorique",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="quantité théorique",
                    ),
                ),
                (
                    "ecart",
                    models.FloatField(
                        blank=True, editable=False, null=True, verbose_name="écart"
                    ),
                ),
                (
                    "inventaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.inventaire",
                        verbose_name="inventaire",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_inventaire",
                        to="stock.lot",
                        verbose_name="lot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
                "verbose_name_plural": "Lignes d'inventaire",
                "ordering": ["inventaire", "lot"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inventaire", "lot"), name="un_lot_par_inventaire"
                    )
                ],
            },
        ),
    ]
