# Generated by Django 5.2.17 on 2026-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_valorisation_transferts_inventaires"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallot",
            name="certificat",
            field=models.TextField(
                blank=True,
                help_text="Certificat de la coulée (PDF ou image).",
                max_length=100,
                verbose_name="certificat matière (3.1)",
            ),
        ),
        migrations.AddField(
            model_name="historicallot",
            name="numero_coulee",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Traçabilité matière : repris sur le bon de livraison et recherchable.",
                max_length=100,
                verbose_name="n° de coulée / de lot fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="certificat",
            field=models.FileField(
                blank=True,
                help_text="Certificat de la coulée (PDF ou image).",
                upload_to="stock/certificats/%Y/",
                verbose_name="certificat matière (3.1)",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="numero_coulee",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Traçabilité matière : repris sur le bon de livraison et recherchable.",
                max_length=100,
                verbose_name="n° de coulée / de lot fournisseur",
            ),
        ),
    ]
