# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_tracabilite_matiere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallot",
            name="cout_unitaire_moyen",
            field=comptes.champs.ChampDecimal(
                decimal_places=4,
                default=0,
                editable=False,
                help_text="Recalculé à chaque entrée valorisée (réception, transfert) ; inchangé par les sorties.",
                max_digits=14,
                verbose_name="coût unitaire moyen pondéré",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="cout_unitaire_moyen",
            field=comptes.champs.ChampDecimal(
                decimal_places=4,
                default=0,
                editable=False,
                help_text="Recalculé à chaque entrée valorisée (réception, transfert) ; inchangé par les sorties.",
                max_digits=14,
                verbose_name="coût unitaire moyen pondéré",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="cout_unitaire",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                help_text="Valorisation d'une entrée (prix d'achat, coût de transfert) ; sert au coût moyen pondéré du lot.",
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="coût unitaire",
            ),
        ),
    ]
