# Generated by Django 5.2.17 on 2026-08-31 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commercial", "0002_contact"),
        ("stock", "0001_initial"),
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_commande", models.DateField()),
                ("date_livraison_prevue", models.DateField(blank=True, null=True)),
                ("statut", models.CharField(blank=True, max_length=50)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_fournisseur",
                        to="commercial.tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande fournisseur",
                "verbose_name_plural": "Commandes fournisseur",
                "ordering": ["-date_commande", "numero"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_commandee", models.FloatField()),
                ("prix_unitaire_achat", models.FloatField()),
                (
                    "quantite_recue",
                    models.FloatField(
                        default=0,
                        editable=False,
                        help_text="Cumul recalculé depuis les réceptions",
                    ),
                ),
                (
                    "alerte_stock_origine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable — clôture l'alerte à la commande",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_commande_fournisseur",
                        to="stock.alertestock",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_commande_fournisseur",
                        to="technique.article",
                    ),
                ),
                (
                    "commande_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="achats.commandefournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande fournisseur",
                "verbose_name_plural": "Lignes de commande fournisseur",
                "ordering": ["commande_fournisseur", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_reception", models.DateField(default=django.utils.timezone.now)),
                (
                    "commande_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="achats.commandefournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réception",
                "verbose_name_plural": "Réceptions",
                "ordering": ["-date_reception", "numero"],
            },
        ),
        migrations.CreateModel(
            name="ReceptionLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_recue", models.FloatField()),
                (
                    "ligne_commande_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions_lignes",
                        to="achats.lignecommandefournisseur",
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="achats.reception",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de réception",
                "verbose_name_plural": "Lignes de réception",
                "ordering": ["reception", "id"],
            },
        ),
    ]
