# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0001_initial"),
        ("commercial", "0003_alter_adresse_adresse_alter_adresse_code_postal_and_more"),
        ("stock", "0002_alter_alertestock_article_and_more"),
        (
            "technique",
            "0002_alter_article_cout_unitaire_alter_article_epaisseur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandefournisseur",
            name="date_commande",
            field=models.DateField(verbose_name="date de commande"),
        ),
        migrations.AlterField(
            model_name="commandefournisseur",
            name="date_livraison_prevue",
            field=models.DateField(
                blank=True, null=True, verbose_name="date de livraison prévue"
            ),
        ),
        migrations.AlterField(
            model_name="commandefournisseur",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes_fournisseur",
                to="commercial.tiers",
                verbose_name="fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="commandefournisseur",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="commandefournisseur",
            name="statut",
            field=models.CharField(blank=True, max_length=50, verbose_name="statut"),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="alerte_stock_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable — clôture l'alerte à la commande",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lignes_commande_fournisseur",
                to="stock.alertestock",
                verbose_name="alerte de stock d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande_fournisseur",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="commande_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="achats.commandefournisseur",
                verbose_name="commande fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="prix_unitaire_achat",
            field=models.FloatField(verbose_name="prix unitaire d'achat"),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="quantite_commandee",
            field=models.FloatField(verbose_name="quantité commandée"),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="quantite_recue",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="Cumul recalculé depuis les réceptions",
                verbose_name="quantité reçue",
            ),
        ),
        migrations.AlterField(
            model_name="reception",
            name="commande_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receptions",
                to="achats.commandefournisseur",
                verbose_name="commande fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="reception",
            name="date_reception",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date de réception"
            ),
        ),
        migrations.AlterField(
            model_name="reception",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="receptionligne",
            name="ligne_commande_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receptions_lignes",
                to="achats.lignecommandefournisseur",
                verbose_name="ligne de commande fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="receptionligne",
            name="quantite_recue",
            field=models.FloatField(verbose_name="quantité reçue"),
        ),
        migrations.AlterField(
            model_name="receptionligne",
            name="reception",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="achats.reception",
                verbose_name="réception",
            ),
        ),
    ]
