# Generated by Django 5.2.17 on 2026-09-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0002_alter_commandefournisseur_date_commande_and_more"),
        ("chiffrage", "0009_synchroniser_lignes_commande_existantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="commande_ligne_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Commande client que cet achat sert à approvisionner (facultatif). Plusieurs lignes de commande fournisseur peuvent pointer vers la même ligne de commande client (réappro en plusieurs fois, ou auprès de plusieurs fournisseurs).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvisionnements",
                to="chiffrage.commandeligne",
                verbose_name="ligne de commande client",
            ),
        ),
    ]
