# Generated by Django 5.2.17 on 2026-09-09 16:38

import django.db.models.deletion
import technique.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0003_lignecommandefournisseur_commande_ligne_client"),
        ("commercial", "0008_delaipropose"),
        ("technique", "0004_alter_article_nature"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="référence fournisseur"
                    ),
                ),
                (
                    "designation_fournisseur",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="désignation fournisseur",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fournisseurs",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles_fournis",
                        to="commercial.tiers",
                        verbose_name="fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur d'article",
                "verbose_name_plural": "Fournisseurs d'article",
                "ordering": ["article", "fournisseur"],
            },
        ),
        migrations.CreateModel(
            name="TarifAchatArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.FloatField(
                        help_text="€, prix d'achat proposé par ce fournisseur",
                        verbose_name="prix unitaire",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "article_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="achats.articlefournisseur",
                        verbose_name="fournisseur de l'article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif d'achat",
                "verbose_name_plural": "Tarifs d'achat",
                "ordering": ["article_fournisseur", "-date_debut"],
            },
            bases=(technique.models.DateRangeHistoriqueMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="articlefournisseur",
            constraint=models.UniqueConstraint(
                fields=("article", "fournisseur"), name="unique_article_fournisseur"
            ),
        ),
    ]
