# Generated by Django 5.2.17 on 2026-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0004_articlefournisseur_tarifachatarticle_and_more"),
        ("comptabilite", "0007_alter_articlecompteachat_code_analytique_and_more"),
        ("technique", "0004_alter_article_nature"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="Libellé libre pour une ligne sans article (ex. « Assurance RC Pro — T1 2026 »).",
                max_length=255,
                verbose_name="désignation",
            ),
        ),
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="poste_gestion",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour une charge générale sans article (assurance, abonnement...).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande_fournisseur",
                to="comptabilite.postegestion",
                verbose_name="poste de gestion",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande_fournisseur",
                to="technique.article",
                verbose_name="article",
            ),
        ),
    ]
