# Generated by Django 5.2.17 on 2026-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0005_lignecommandefournisseur_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifachatarticle",
            name="frais_port",
            field=models.FloatField(
                blank=True,
                help_text="€, forfait de livraison associé à ce tarif (facultatif)",
                null=True,
                verbose_name="frais de port",
            ),
        ),
    ]
