# Generated by Django 5.2.17 on 2026-09-10 10:05

import achats.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0006_tarifachatarticle_frais_port"),
        ("commercial", "0013_seed_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="taux_tva",
            field=models.ForeignKey(
                blank=True,
                default=achats.models._taux_tva_par_defaut,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande_fournisseur",
                to="commercial.tauxtva",
                verbose_name="taux de TVA",
            ),
        ),
        migrations.CreateModel(
            name="FactureFournisseur",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="numéro",
                    ),
                ),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de facture tel qu'indiqué par le fournisseur (distinct du numéro interne ci-dessus)",
                        max_length=100,
                        verbose_name="référence fournisseur",
                    ),
                ),
                ("date_facture", models.DateField(verbose_name="date de facture")),
                (
                    "montant_ht",
                    models.FloatField(blank=True, null=True, verbose_name="montant HT"),
                ),
                (
                    "montant_ttc",
                    models.FloatField(
                        blank=True, null=True, verbose_name="montant TTC"
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="statut de paiement"
                    ),
                ),
                (
                    "commande_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="achats.commandefournisseur",
                        verbose_name="commande fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture fournisseur",
                "verbose_name_plural": "Factures fournisseur",
                "ordering": ["-date_facture", "numero"],
            },
        ),
    ]
