# Generated by Django 5.2.17 on 2026-10-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_lignecommandefournisseur_taux_tva_facturefournisseur"),
        ("stock", "0005_tracabilite_matiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptionligne",
            name="certificat",
            field=models.FileField(
                blank=True,
                help_text="Rattaché au lot de la coulée s'il n'en a pas encore.",
                upload_to="stock/certificats/%Y/",
                verbose_name="certificat matière (3.1)",
            ),
        ),
        migrations.AddField(
            model_name="receptionligne",
            name="emplacement",
            field=models.ForeignKey(
                blank=True,
                help_text="Emplacement du lot, nécessaire pour créer un nouveau lot.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receptions_lignes",
                to="stock.emplacement",
                verbose_name="emplacement",
            ),
        ),
        migrations.AddField(
            model_name="receptionligne",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lot existant qui reçoit cette quantité. Laisser vide pour le déduire du n° de coulée.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receptions_lignes",
                to="stock.lot",
                verbose_name="lot de destination",
            ),
        ),
        migrations.AddField(
            model_name="receptionligne",
            name="numero_coulee",
            field=models.CharField(
                blank=True,
                help_text="Un n° déjà connu complète son lot ; un nouveau n° crée un lot (traçabilité matière).",
                max_length=100,
                verbose_name="n° de coulée",
            ),
        ),
    ]
