# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0008_tracabilite_matiere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturefournisseur",
            name="montant_ht",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="facturefournisseur",
            name="montant_ttc",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="montant TTC",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommandefournisseur",
            name="prix_unitaire_achat",
            field=comptes.champs.ChampDecimal(
                decimal_places=4, max_digits=14, verbose_name="prix unitaire d'achat"
            ),
        ),
        migrations.AlterField(
            model_name="tarifachatarticle",
            name="frais_port",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="€, forfait de livraison associé à ce tarif (facultatif)",
                max_digits=14,
                null=True,
                verbose_name="frais de port",
            ),
        ),
        migrations.AlterField(
            model_name="tarifachatarticle",
            name="prix_unitaire",
            field=comptes.champs.ChampDecimal(
                decimal_places=4,
                help_text="€, prix d'achat proposé par ce fournisseur",
                max_digits=14,
                verbose_name="prix unitaire",
            ),
        ),
    ]
