# Generated by Django 5.2.17 on 2026-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0009_passage_en_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturefournisseur",
            name="date_paiement",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle la facture a été réglée au fournisseur : elle alimente le journal de banque de l'export comptable.",
                null=True,
                verbose_name="date de règlement",
            ),
        ),
    ]
