# Generated by Django 5.2.17 on 2026-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0010_facturefournisseur_date_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturefournisseur",
            name="autoliquidation",
            field=models.BooleanField(
                blank=True,
                help_text="Facture d'un fournisseur étranger sans TVA : l'ERP comptabilise la TVA à la fois déductible et due. Vide : automatique selon le régime fiscal du fournisseur (intracommunautaire ou hors UE : oui). Choisir « Non » pour une importation de marchandises dont la TVA est payée à la douane.",
                null=True,
                verbose_name="autoliquidation de la TVA",
            ),
        ),
    ]
