# Generated by Django 5.2.17 on 2026-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegleCodification",
            fields=[
                (
                    "entite",
                    models.CharField(
                        choices=[
                            ("devis", "Devis"),
                            ("commande", "Commande"),
                            ("ordre_fabrication", "Ordre de fabrication"),
                            ("commande_fournisseur", "Commande fournisseur"),
                            ("reception", "Réception"),
                            ("facture", "Facture"),
                            ("envoi_sous_traitance", "Envoi sous-traitance"),
                            ("retour_sous_traitance", "Retour sous-traitance"),
                            ("tiers", "Tiers"),
                            ("emplacement", "Emplacement"),
                        ],
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="entité",
                    ),
                ),
                (
                    "prefixe",
                    models.CharField(
                        blank=True,
                        help_text='Ex. "DEV-"',
                        max_length=20,
                        verbose_name="préfixe",
                    ),
                ),
                (
                    "nombre_chiffres",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Largeur du numéro, complété par des zéros à gauche (ex. 5 → 00001)",
                        verbose_name="nombre de chiffres",
                    ),
                ),
                (
                    "reinitialisation",
                    models.CharField(
                        choices=[
                            ("jamais", "Jamais (compteur continu)"),
                            ("annuelle", "Chaque année"),
                        ],
                        default="jamais",
                        help_text="Si annuelle, l'année en cours (4 chiffres) est insérée entre le préfixe et le numéro",
                        max_length=20,
                        verbose_name="réinitialisation",
                    ),
                ),
                (
                    "compteur_actuel",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Dernier numéro attribué — le prochain code proposé utilisera compteur + 1",
                        verbose_name="compteur actuel",
                    ),
                ),
                (
                    "annee_compteur",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        help_text="Année sur laquelle porte le compteur actuel (réinitialisation annuelle uniquement)",
                        null=True,
                        verbose_name="année du compteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de codification",
                "verbose_name_plural": "Règles de codification",
                "ordering": ["entite"],
            },
        ),
    ]
