# Generated by Django 5.2.17 on 2026-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codification", "0003_seed_regle_livraison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglecodification",
            name="entite",
            field=models.CharField(
                choices=[
                    ("devis", "Devis"),
                    ("commande", "Commande"),
                    ("ordre_fabrication", "Ordre de fabrication"),
                    ("commande_fournisseur", "Commande fournisseur"),
                    ("reception", "Réception"),
                    ("livraison", "Livraison"),
                    ("facture", "Facture"),
                    ("envoi_sous_traitance", "Envoi sous-traitance"),
                    ("retour_sous_traitance", "Retour sous-traitance"),
                    ("tiers", "Tiers"),
                    ("emplacement", "Emplacement"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
                verbose_name="entité",
            ),
        ),
    ]
