# Generated by Django 5.2.17 on 2026-10-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codification", "0006_seed_regle_facture_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglecodification",
            name="format_annee",
            field=models.CharField(
                choices=[("4", "4 chiffres (2026)"), ("2", "2 chiffres (26)")],
                default="4",
                help_text="Réinitialisation annuelle seulement : 2026 ou 26. Ex. préfixe « DC », 2 chiffres → DC26-0001.",
                max_length=1,
                verbose_name="année dans le code",
            ),
        ),
        migrations.AlterField(
            model_name="reglecodification",
            name="reinitialisation",
            field=models.CharField(
                choices=[
                    ("jamais", "Jamais (compteur continu)"),
                    ("annuelle", "Chaque année"),
                ],
                default="jamais",
                help_text="Si annuelle, l'année en cours est insérée entre le préfixe et le numéro (ex. DC26-0001)",
                max_length=20,
                verbose_name="réinitialisation",
            ),
        ),
    ]
