# Generated by Django 5.2.17 on 2026-08-29 19:37

import django.db.models.deletion
import technique.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "densite",
                    models.FloatField(
                        help_text="kg/dm³, utilisée pour le calcul au poids"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="PosteTravail",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type_operation", models.CharField(blank=True, max_length=100)),
                (
                    "mode_calcul",
                    models.CharField(
                        choices=[
                            ("horaire", "Horaire"),
                            ("forfaitaire", "Forfaitaire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nombre_machines",
                    models.PositiveIntegerField(
                        default=1, help_text="Capacité agrégée (usage planning)"
                    ),
                ),
                (
                    "taux_marge_defaut",
                    models.FloatField(
                        blank=True,
                        help_text="Marge par défaut sur les opérations de ce poste",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste de travail",
                "verbose_name_plural": "Postes de travail",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "reference",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("matiere_premiere", "Matière première"),
                            ("fabrique", "Fabriqué"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unite_cout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("surface", "Surface"),
                            ("longueur", "Longueur"),
                            ("poids", "Poids"),
                            ("piece", "Pièce"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "epaisseur",
                    models.FloatField(blank=True, help_text="Tôle", null=True),
                ),
                (
                    "type_profil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tube_carre", "Tube carré"),
                            ("tube_rectangulaire", "Tube rectangulaire"),
                            ("corniere", "Cornière"),
                            ("profil_i", "Profilé I"),
                            ("profil_u", "Profilé U"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "poids_lineique",
                    models.FloatField(
                        blank=True,
                        help_text="kg/mètre (profilés vendus au poids)",
                        null=True,
                    ),
                ),
                (
                    "cout_unitaire",
                    models.FloatField(
                        blank=True,
                        help_text="Coût d'achat (matière première)",
                        null=True,
                    ),
                ),
                (
                    "taux_marge_defaut",
                    models.FloatField(
                        blank=True,
                        help_text="Marge par défaut sur le coût matière (articles fabriqués)",
                        null=True,
                    ),
                ),
                (
                    "gere_en_stock",
                    models.BooleanField(
                        blank=True,
                        help_text="Vrai par défaut pour une matière première, faux par défaut pour un fabriqué, modifiable au cas par cas. Laisser vide pour appliquer le défaut.",
                        null=True,
                    ),
                ),
                (
                    "stock_mini",
                    models.FloatField(
                        blank=True,
                        help_text="Seuil d'alerte de réapprovisionnement",
                        null=True,
                    ),
                ),
                (
                    "quantite_reappro",
                    models.FloatField(
                        blank=True, help_text="Quantité suggérée à commander", null=True
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pertinent pour tôles/profilés",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="technique.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longueur_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Tôle (avec largeur) ou profilé (seule)",
                        null=True,
                    ),
                ),
                (
                    "largeur_mm",
                    models.FloatField(
                        blank=True, help_text="Tôle uniquement", null=True
                    ),
                ),
                (
                    "quantite",
                    models.FloatField(help_text="Nombre de pièces/découpes identiques"),
                ),
                (
                    "article_composant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilise_dans",
                        to="technique.article",
                    ),
                ),
                (
                    "article_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composants",
                        to="technique.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de nomenclature",
                "verbose_name_plural": "Nomenclatures",
                "ordering": ["article_parent", "article_composant"],
            },
        ),
        migrations.CreateModel(
            name="Gamme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField()),
                (
                    "temps_fixe",
                    models.FloatField(
                        blank=True, help_text="Réglage (mode horaire)", null=True
                    ),
                ),
                (
                    "temps_variable",
                    models.FloatField(
                        blank=True, help_text="Temps unitaire (mode horaire)", null=True
                    ),
                ),
                (
                    "cout_forfaitaire",
                    models.FloatField(
                        blank=True,
                        help_text="Mode forfaitaire (sous-traitance)",
                        null=True,
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True, help_text="Historisation de la révision", null=True
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamme_etapes",
                        to="technique.article",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gamme_etapes",
                        to="technique.postetravail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de gamme",
                "verbose_name_plural": "Gammes",
                "ordering": ["article", "ordre", "-date_debut"],
            },
            bases=(technique.models.DateRangeHistoriqueMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TarifPoste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cout_horaire", models.FloatField(help_text="€/heure")),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="technique.postetravail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif de poste",
                "verbose_name_plural": "Tarifs de poste",
                "ordering": ["poste", "-date_debut"],
            },
            bases=(technique.models.DateRangeHistoriqueMixin, models.Model),
        ),
    ]
