# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cout_unitaire",
            field=models.FloatField(
                blank=True,
                help_text="Coût d'achat (matière première)",
                null=True,
                verbose_name="coût unitaire",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="epaisseur",
            field=models.FloatField(
                blank=True, help_text="Tôle", null=True, verbose_name="épaisseur"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="gere_en_stock",
            field=models.BooleanField(
                blank=True,
                help_text="Vrai par défaut pour une matière première, faux par défaut pour un fabriqué, modifiable au cas par cas. Laisser vide pour appliquer le défaut.",
                null=True,
                verbose_name="géré en stock",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                help_text="Pertinent pour tôles/profilés",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="technique.matiere",
                verbose_name="matière",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="nature",
            field=models.CharField(
                choices=[
                    ("matiere_premiere", "Matière première"),
                    ("fabrique", "Fabriqué"),
                ],
                max_length=20,
                verbose_name="nature",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="poids_lineique",
            field=models.FloatField(
                blank=True,
                help_text="kg/mètre (profilés vendus au poids)",
                null=True,
                verbose_name="poids linéique",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="quantite_reappro",
            field=models.FloatField(
                blank=True,
                help_text="Quantité suggérée à commander",
                null=True,
                verbose_name="quantité de réapprovisionnement",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="reference",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="référence",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="stock_mini",
            field=models.FloatField(
                blank=True,
                help_text="Seuil d'alerte de réapprovisionnement",
                null=True,
                verbose_name="stock minimum",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="taux_marge_defaut",
            field=models.FloatField(
                blank=True,
                help_text="Marge par défaut sur le coût matière (articles fabriqués)",
                null=True,
                verbose_name="taux de marge par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="type_profil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tube_carre", "Tube carré"),
                    ("tube_rectangulaire", "Tube rectangulaire"),
                    ("corniere", "Cornière"),
                    ("profil_i", "Profilé I"),
                    ("profil_u", "Profilé U"),
                ],
                max_length=20,
                null=True,
                verbose_name="type de profil",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="unite_cout",
            field=models.CharField(
                blank=True,
                choices=[
                    ("surface", "Surface"),
                    ("longueur", "Longueur"),
                    ("poids", "Poids"),
                    ("piece", "Pièce"),
                ],
                max_length=20,
                null=True,
                verbose_name="unité de coût",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamme_etapes",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="cout_forfaitaire",
            field=models.FloatField(
                blank=True,
                help_text="Mode forfaitaire (sous-traitance)",
                null=True,
                verbose_name="coût forfaitaire",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="date_debut",
            field=models.DateField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="date_fin",
            field=models.DateField(
                blank=True,
                help_text="Historisation de la révision",
                null=True,
                verbose_name="date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="ordre",
            field=models.PositiveIntegerField(verbose_name="ordre"),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gamme_etapes",
                to="technique.postetravail",
                verbose_name="poste",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="temps_fixe",
            field=models.FloatField(
                blank=True,
                help_text="Réglage (mode horaire)",
                null=True,
                verbose_name="temps fixe",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="temps_variable",
            field=models.FloatField(
                blank=True,
                help_text="Temps unitaire (mode horaire)",
                null=True,
                verbose_name="temps variable",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="densite",
            field=models.FloatField(
                help_text="kg/dm³, utilisée pour le calcul au poids",
                verbose_name="densité",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="nom",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="article_composant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilise_dans",
                to="technique.article",
                verbose_name="article composant",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="article_parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="composants",
                to="technique.article",
                verbose_name="article parent",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="largeur_mm",
            field=models.FloatField(
                blank=True,
                help_text="Tôle uniquement",
                null=True,
                verbose_name="largeur (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="longueur_mm",
            field=models.FloatField(
                blank=True,
                help_text="Tôle (avec largeur) ou profilé (seule)",
                null=True,
                verbose_name="longueur (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="quantite",
            field=models.FloatField(
                help_text="Nombre de pièces/découpes identiques",
                verbose_name="quantité",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="mode_calcul",
            field=models.CharField(
                choices=[("horaire", "Horaire"), ("forfaitaire", "Forfaitaire")],
                max_length=20,
                verbose_name="mode de calcul",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="nom",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="nombre_machines",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Capacité agrégée (usage planning)",
                verbose_name="nombre de machines",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="taux_marge_defaut",
            field=models.FloatField(
                blank=True,
                help_text="Marge par défaut sur les opérations de ce poste",
                null=True,
                verbose_name="taux de marge par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="type_operation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="type d'opération"
            ),
        ),
        migrations.AlterField(
            model_name="tarifposte",
            name="cout_horaire",
            field=models.FloatField(help_text="€/heure", verbose_name="coût horaire"),
        ),
        migrations.AlterField(
            model_name="tarifposte",
            name="date_debut",
            field=models.DateField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="tarifposte",
            name="date_fin",
            field=models.DateField(blank=True, null=True, verbose_name="date de fin"),
        ),
        migrations.AlterField(
            model_name="tarifposte",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="technique.postetravail",
                verbose_name="poste",
            ),
        ),
    ]
