# Generated by Django 5.2.17 on 2026-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "technique",
            "0002_alter_article_cout_unitaire_alter_article_epaisseur_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="libelle",
            field=models.CharField(
                blank=True,
                help_text="Nom/description lisible de l'article, en plus de la référence",
                max_length=200,
                verbose_name="libellé",
            ),
        ),
    ]
