# Generated by Django 5.2.17 on 2026-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0003_article_libelle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="nature",
            field=models.CharField(
                choices=[
                    ("matiere_premiere", "Matière première"),
                    ("fabrique", "Fabriqué"),
                    ("service_achete", "Service acheté"),
                    ("consommable", "Consommable"),
                    ("composant", "Composant"),
                ],
                max_length=20,
                verbose_name="nature",
            ),
        ),
    ]
