# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0005_article_taux_tva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cout_unitaire",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                help_text="Coût d'achat (matière première)",
                max_digits=14,
                null=True,
                verbose_name="coût unitaire",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="taux_marge_defaut",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Marge par défaut sur le coût matière (articles fabriqués)",
                max_digits=7,
                null=True,
                verbose_name="taux de marge par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="gamme",
            name="cout_forfaitaire",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                help_text="Mode forfaitaire (sous-traitance)",
                max_digits=14,
                null=True,
                verbose_name="coût forfaitaire",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="taux_marge_defaut",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Marge par défaut sur les opérations de ce poste",
                max_digits=7,
                null=True,
                verbose_name="taux de marge par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="tarifposte",
            name="cout_horaire",
            field=comptes.champs.ChampDecimal(
                decimal_places=4,
                help_text="€/heure",
                max_digits=14,
                verbose_name="coût horaire",
            ),
        ),
    ]
