# Generated by Django 5.2.17 on 2026-10-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0006_passage_en_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamme",
            name="origine",
            field=models.CharField(
                choices=[
                    ("manuelle", "Saisie à la main"),
                    ("decoupe", "Calculée depuis la pièce à découper"),
                ],
                default="manuelle",
                help_text="Une étape « calculée » est remise à jour depuis la pièce à découper (temps de coupe) ; la modifier à la main la fait revenir en « saisie à la main ».",
                max_length=12,
                verbose_name="origine",
            ),
        ),
    ]
