# Generated by Django 5.2.17 on 2026-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0007_gamme_origine"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="usinabilite",
            field=models.FloatField(
                blank=True,
                help_text="Indice d'usinabilité au jet d'eau (acier 87,6 ; inox 81,9 ; cuivre/laiton 110 ; aluminium 213…) : sert à calculer les vitesses de coupe quand elles n'ont pas été relevées sur la machine.",
                null=True,
                verbose_name="usinabilité",
            ),
        ),
    ]
