# Generated by Django 5.2.17 on 2026-10-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0008_matiere_usinabilite"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilleMatiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "nom_igems",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la matière dans materials.lua (Steel, Stainless Steel, Aluminium…) : sert à l'import de la base de coupe.",
                        max_length=100,
                        verbose_name="nom dans le logiciel de la machine",
                    ),
                ),
                (
                    "usinabilite",
                    models.FloatField(
                        blank=True,
                        help_text="Indice d'usinabilité au jet d'eau",
                        null=True,
                        verbose_name="usinabilité standard",
                    ),
                ),
                (
                    "mots_cles",
                    models.TextField(
                        blank=True,
                        help_text="Un par ligne ou séparés par des virgules (ex. s235, s355, acier, steel). Une nuance dont le nom commence par l'un d'eux est rattachée à cette famille. Les expressions à plusieurs mots (« en aw ») se cherchent dans le nom entier.",
                        verbose_name="mots-clés des nuances",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Les familles de priorité faible sont essayées d'abord (« inox » avant « acier »).",
                        verbose_name="priorité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Famille de matière",
                "verbose_name_plural": "Familles de matière",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AlterField(
            model_name="matiere",
            name="usinabilite",
            field=models.FloatField(
                blank=True,
                help_text="Indice d'usinabilité au jet d'eau (acier 87,6 ; inox 81,9 ; cuivre/laiton 110 ; aluminium 213…) : sert à calculer les vitesses de coupe quand elles n'ont pas été relevées sur la machine. Vide : celle de la famille.",
                null=True,
                verbose_name="usinabilité",
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="famille",
            field=models.ForeignKey(
                blank=True,
                help_text="Matière générique dont cette nuance hérite les paramètres de coupe (S235 → Acier, 5754 → Aluminium…). Rattachée automatiquement d'après le nom à la création si elle est laissée vide.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuances",
                to="technique.famillematiere",
                verbose_name="famille de matière",
            ),
        ),
    ]
