# Generated by Django 5.2.17 on 2026-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0010_familles_matiere_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="famillematiere",
            name="gaz_laser_prefere",
            field=models.CharField(
                blank=True,
                choices=[("O2", "Oxygène"), ("N2", "Azote"), ("Air", "Air comprimé")],
                help_text="Gaz retenu au laser quand la pièce n'en précise pas (oxygène pour l'acier, azote pour l'inox et l'alu…).",
                max_length=4,
                verbose_name="gaz de coupe laser usuel",
            ),
        ),
    ]
