# Generated by Django 5.2.17 on 2026-10-08 05:27

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0012_familles_laser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="taux_marge_defaut",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="En pourcentage du coût : 20 = prix de vente × 1,20. Marge par défaut sur le coût matière (articles fabriqués)",
                max_digits=7,
                null=True,
                verbose_name="taux de marge par défaut (%)",
            ),
        ),
        migrations.AlterField(
            model_name="postetravail",
            name="taux_marge_defaut",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="En pourcentage du coût : 20 = prix de vente × 1,20. Marge par défaut sur les opérations de ce poste",
                max_digits=7,
                null=True,
                verbose_name="taux de marge par défaut (%)",
            ),
        ),
    ]
