# Generated by Django 5.2.17 on 2026-10-09 10:40

import comptes.champs
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0013_alter_article_taux_marge_defaut_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GammeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamme type",
                "verbose_name_plural": "Gammes types",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="GammeTypeEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(verbose_name="ordre")),
                (
                    "temps_fixe",
                    models.FloatField(
                        blank=True,
                        help_text="Réglage (poste horaire)",
                        null=True,
                        verbose_name="temps fixe (min)",
                    ),
                ),
                (
                    "temps_variable",
                    models.FloatField(
                        blank=True,
                        help_text="Poste horaire",
                        null=True,
                        verbose_name="temps par pièce (min)",
                    ),
                ),
                (
                    "cout_forfaitaire",
                    comptes.champs.ChampDecimal(
                        blank=True,
                        decimal_places=4,
                        help_text="Poste forfaitaire (sous-traitance)",
                        max_digits=14,
                        null=True,
                        verbose_name="coût forfaitaire par pièce",
                    ),
                ),
                (
                    "gamme_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="technique.gammetype",
                        verbose_name="gamme type",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gamme_type_etapes",
                        to="technique.postetravail",
                        verbose_name="poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de gamme type",
                "verbose_name_plural": "Étapes de gamme type",
                "ordering": ["gamme_type", "ordre"],
            },
        ),
    ]
