# Generated by Django 5.2.17 on 2026-10-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0014_gammes_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="postetravail",
            name="temps_mise_en_place_min",
            field=models.FloatField(
                blank=True,
                help_text="Machines de découpe (laser, jet d'eau) : temps de réglage appliqué UNE fois par tôle posée sur la machine, quel que soit le nombre de pièces qu'elle contient. Peut être précisé par épaisseur dans les paramètres de coupe.",
                null=True,
                verbose_name="mise en place d'une tôle (min)",
            ),
        ),
    ]
