# Generated by Django 5.2.17 on 2026-10-10 09:27

import comptes.champs
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0019_passage_en_decimal"),
        ("technique", "0016_reprendre_reglage_decoupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegleCreationTole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex. « Inox au kilo », « Acier standard »",
                        max_length=100,
                        verbose_name="nom",
                    ),
                ),
                (
                    "epaisseur_min",
                    models.FloatField(
                        blank=True,
                        help_text="Vide : sans minimum.",
                        null=True,
                        verbose_name="épaisseur min (mm)",
                    ),
                ),
                (
                    "epaisseur_max",
                    models.FloatField(
                        blank=True,
                        help_text="Vide : sans maximum.",
                        null=True,
                        verbose_name="épaisseur max (mm)",
                    ),
                ),
                (
                    "modele_reference",
                    models.CharField(
                        default="TOLE-{matiere}-{epaisseur}",
                        help_text="Variables : {matiere}, {famille}, {epaisseur} (3, 2.5…). Une référence déjà prise reçoit un suffixe -2, -3…",
                        max_length=80,
                        verbose_name="modèle de référence",
                    ),
                ),
                (
                    "modele_libelle",
                    models.CharField(
                        blank=True,
                        default="Tôle {matiere} {epaisseur} mm",
                        help_text="Mêmes variables ; l'épaisseur s'écrit avec une virgule (2,5).",
                        max_length=120,
                        verbose_name="modèle de libellé",
                    ),
                ),
                (
                    "unite_cout",
                    models.CharField(
                        choices=[
                            ("surface", "Surface"),
                            ("longueur", "Longueur"),
                            ("poids", "Poids"),
                            ("piece", "Pièce"),
                        ],
                        default="poids",
                        help_text="Poids : €/kg (la tôle est valorisée d'après sa densité et son épaisseur). Surface : €/m². Pièce : prix de la feuille entière.",
                        max_length=20,
                        verbose_name="unité de coût",
                    ),
                ),
                (
                    "cout_unitaire",
                    comptes.champs.ChampDecimal(
                        blank=True,
                        decimal_places=4,
                        help_text="Dans l'unité ci-dessus. Vide : à renseigner sur chaque tôle créée.",
                        max_digits=14,
                        null=True,
                        verbose_name="coût unitaire d'achat",
                    ),
                ),
                (
                    "gere_en_stock",
                    models.BooleanField(
                        blank=True,
                        help_text="Vide : défaut d'une matière première.",
                        null=True,
                        verbose_name="géré en stock",
                    ),
                ),
                (
                    "stock_mini",
                    models.FloatField(
                        blank=True, null=True, verbose_name="stock minimum"
                    ),
                ),
                (
                    "quantite_reappro",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="quantité de réapprovisionnement",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="active")),
                (
                    "famille",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide et sans nuance : toutes les matières.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_tole",
                        to="technique.famillematiere",
                        verbose_name="famille de matière",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. 1.4307 : prime sur la règle de sa famille.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_tole",
                        to="technique.matiere",
                        verbose_name="nuance précise",
                    ),
                ),
                (
                    "taux_tva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="commercial.tauxtva",
                        verbose_name="taux de TVA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de création de tôle",
                "verbose_name_plural": "Règles de création de tôle",
                "ordering": ["nom"],
            },
        ),
    ]
