# Generated by Django 5.2.17 on 2026-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0017_regle_creation_tole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="unite_cout",
            field=models.CharField(
                blank=True,
                choices=[
                    ("surface", "Au m² (€/m²)"),
                    ("longueur", "Au mètre (€/m)"),
                    ("poids", "Au kilo (€/kg)"),
                    ("piece", "À l'unité (€/pièce)"),
                ],
                help_text="Comment le prix d'achat est exprimé. À l'unité, pour une tôle : prix de la feuille entière.",
                max_length=20,
                null=True,
                verbose_name="unité de coût",
            ),
        ),
        migrations.AlterField(
            model_name="reglecreationtole",
            name="unite_cout",
            field=models.CharField(
                choices=[
                    ("surface", "Au m² (€/m²)"),
                    ("longueur", "Au mètre (€/m)"),
                    ("poids", "Au kilo (€/kg)"),
                    ("piece", "À l'unité (€/pièce)"),
                ],
                default="poids",
                help_text="Poids : €/kg (la tôle est valorisée d'après sa densité et son épaisseur). Surface : €/m². Pièce : prix de la feuille entière.",
                max_length=20,
                verbose_name="unité de coût",
            ),
        ),
    ]
