# Generated by Django 5.2.17 on 2026-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0020_profilesection_table_et_droits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilesection",
            name="dimensions",
            field=models.JSONField(
                default=dict,
                help_text="Cornière : a, b, e. UPN, IPE, HEA, HEB : h, b, tw, tf. Tube carré : c, e. Tube rectangulaire : h, b, e. Tube rond : d, e. Plat : l, e. Rond plein : d. Carré plein : c.",
                verbose_name="cotes (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="profilesection",
            name="famille",
            field=models.CharField(
                choices=[
                    ("corniere", "Cornière à ailes égales"),
                    ("corniere_inegale", "Cornière à ailes inégales"),
                    ("upn", "UPN"),
                    ("ipe", "IPE"),
                    ("hea", "HEA"),
                    ("heb", "HEB"),
                    ("tube_carre", "Tube carré"),
                    ("tube_rectangulaire", "Tube rectangulaire"),
                    ("tube_rond", "Tube rond"),
                    ("plat", "Plat"),
                    ("rond_plein", "Rond plein"),
                    ("carre_plein", "Carré plein"),
                ],
                max_length=20,
                verbose_name="famille",
            ),
        ),
        migrations.AlterField(
            model_name="profilesection",
            name="masse_lineique",
            field=models.FloatField(
                help_text="Masse d'un mètre en acier (7,85 kg/dm³) ; l'aluminium et l'inox s'en déduisent par la densité de la matière.",
                verbose_name="masse linéique, acier (kg/m)",
            ),
        ),
    ]
