# Generated by Django 5.2.17 on 2026-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0023_catalogue_arcelor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglecreationtole",
            name="modele_libelle",
            field=models.CharField(
                blank=True,
                default="Tôle {matiere} - {largeur} x {longueur} x {epaisseur} mm",
                help_text="Mêmes variables ; l'épaisseur s'écrit avec une virgule (2,5).",
                max_length=120,
                verbose_name="modèle de libellé",
            ),
        ),
        migrations.AlterField(
            model_name="reglecreationtole",
            name="modele_reference",
            field=models.CharField(
                default="{matiere} - {largeur} x {longueur} x {epaisseur}",
                help_text="Variables : {matiere}, {famille}, {largeur}, {longueur} (format de tôle, en mm), {epaisseur} (3, 2.5…). Par défaut, la convention « Nuance - largeur x longueur x épaisseur » (S235 - 1500 x 3000 x 3). Une référence déjà prise reçoit un suffixe -2, -3…",
                max_length=80,
                verbose_name="modèle de référence",
            ),
        ),
    ]
