# Generated by Django 5.2.17 on 2026-10-03 14:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalModeleDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("devis", "Devis"),
                            ("ar_commande", "AR de commande"),
                            ("bon_preparation", "Bon de préparation"),
                            ("bon_livraison", "Bon de livraison"),
                            ("fiche_fabrication", "Fiche de fabrication"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="document",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=False,
                        help_text="Décoché : le PDF d'origine est utilisé. Cochez après avoir vérifié l'aperçu.",
                        verbose_name="utiliser ce modèle",
                    ),
                ),
                ("html", models.TextField(blank=True, verbose_name="HTML")),
                ("css", models.TextField(blank=True, verbose_name="CSS")),
                (
                    "projet",
                    models.TextField(
                        blank=True,
                        help_text="Pour rouvrir l'éditeur à l'identique.",
                        verbose_name="projet de l'éditeur",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modifié le"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modèle de document",
                "verbose_name_plural": "historical Modèles de documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ModeleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("devis", "Devis"),
                            ("ar_commande", "AR de commande"),
                            ("bon_preparation", "Bon de préparation"),
                            ("bon_livraison", "Bon de livraison"),
                            ("fiche_fabrication", "Fiche de fabrication"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="document",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=False,
                        help_text="Décoché : le PDF d'origine est utilisé. Cochez après avoir vérifié l'aperçu.",
                        verbose_name="utiliser ce modèle",
                    ),
                ),
                ("html", models.TextField(blank=True, verbose_name="HTML")),
                ("css", models.TextField(blank=True, verbose_name="CSS")),
                (
                    "projet",
                    models.TextField(
                        blank=True,
                        help_text="Pour rouvrir l'éditeur à l'identique.",
                        verbose_name="projet de l'éditeur",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de document",
                "verbose_name_plural": "Modèles de documents",
                "ordering": ["type_document"],
            },
        ),
    ]
