# Generated by Django 5.2.17 on 2026-09-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalComptable",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("achats", "Achats"),
                            ("ventes", "Ventes"),
                            ("banque", "Banque"),
                            ("caisse", "Caisse"),
                            ("notes_de_frais", "Notes de frais"),
                            ("operations_diverses", "Opérations diverses"),
                            ("reports_a_nouveau", "Reports à nouveaux"),
                        ],
                        max_length=30,
                        verbose_name="nature du journal",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="état")),
            ],
            options={
                "verbose_name": "Journal comptable",
                "verbose_name_plural": "Journaux comptables",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("libelle", models.CharField(max_length=255, verbose_name="libellé")),
                (
                    "classe",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        help_text="1er chiffre du code (1 à 8) — déduite automatiquement du code",
                        verbose_name="classe",
                    ),
                ),
                (
                    "systeme",
                    models.CharField(
                        choices=[
                            ("minimal", "Système de base"),
                            ("facultatif", "Système développé"),
                        ],
                        default="minimal",
                        help_text="Système de base (comptes obligatoires) ou développé (détail facultatif) du PCG",
                        max_length=20,
                        verbose_name="système",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "compte_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_comptes",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptable",
                "verbose_name_plural": "Plan comptable",
                "ordering": ["code"],
            },
        ),
    ]
