# Generated by Django 5.2.17 on 2026-09-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0002_seed_journaux_par_defaut"),
        ("facturation", "0002_alter_facture_commande_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ecriture", models.DateField(verbose_name="date d'écriture")),
                (
                    "piece",
                    models.CharField(
                        help_text="Référence de la pièce justificative (ex. numéro de facture)",
                        max_length=50,
                        verbose_name="pièce",
                    ),
                ),
                ("libelle", models.CharField(max_length=255, verbose_name="libellé")),
                (
                    "facture",
                    models.OneToOneField(
                        blank=True,
                        help_text="Renseigné automatiquement pour une écriture générée depuis une facture (empêche sa double génération).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecriture_comptable",
                        to="facturation.facture",
                        verbose_name="facture d'origine",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="comptabilite.journalcomptable",
                        verbose_name="journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-date_ecriture", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="libellé"
                    ),
                ),
                ("debit", models.FloatField(default=0, verbose_name="débit")),
                ("credit", models.FloatField(default=0, verbose_name="crédit")),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_ecriture",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite.ecriturecomptable",
                        verbose_name="écriture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "ordering": ["ecriture", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParametresComptables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compte_client_defaut",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. 411 — Clients",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte client par défaut",
                    ),
                ),
                (
                    "compte_tva_collectee_defaut",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. 44571 — TVA collectée",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de TVA collectée par défaut",
                    ),
                ),
                (
                    "compte_vente_defaut",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. 706 — Prestations de services",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente par défaut",
                    ),
                ),
                (
                    "journal_ventes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.journalcomptable",
                        verbose_name="journal des ventes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres comptables",
                "verbose_name_plural": "Paramètres comptables",
            },
        ),
    ]
