# Generated by Django 5.2.17 on 2026-09-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0004_seed_parametres_comptables"),
        ("technique", "0004_alter_article_nature"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCompteVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compte_vente_override",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "compte_vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de vente d'article",
                "verbose_name_plural": "Comptes de vente d'article",
                "ordering": ["article"],
            },
        ),
    ]
