# Generated by Django 5.2.17 on 2026-09-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0005_articlecomptevente"),
        ("technique", "0004_alter_article_nature"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeAnalytique",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="libellé")),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "Code analytique",
                "verbose_name_plural": "Codes analytiques",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCompteAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compte_achat_override",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "compte_achat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte d'achat",
                    ),
                ),
                (
                    "code_analytique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.codeanalytique",
                        verbose_name="code analytique par défaut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte d'achat d'article",
                "verbose_name_plural": "Comptes d'achat d'article",
                "ordering": ["article"],
            },
        ),
        migrations.AddField(
            model_name="articlecomptevente",
            name="code_analytique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.codeanalytique",
                verbose_name="code analytique par défaut",
            ),
        ),
        migrations.AddField(
            model_name="ligneecriture",
            name="code_analytique",
            field=models.ForeignKey(
                blank=True,
                help_text="Axe complémentaire optionnel — atelier, chantier, centre de coût...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_ecriture",
                to="comptabilite.codeanalytique",
                verbose_name="code analytique",
            ),
        ),
    ]
