# Generated by Django 5.2.17 on 2026-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0006_codeanalytique_articlecompteachat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecompteachat",
            name="code_analytique",
            field=models.ForeignKey(
                blank=True,
                help_text="Prioritaire sur le code analytique du poste de gestion, s'il y en a un.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.codeanalytique",
                verbose_name="code analytique par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="articlecompteachat",
            name="compte_achat",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisé seulement si aucun poste de gestion n'est renseigné ci-dessus.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte d'achat (fixe)",
            ),
        ),
        migrations.AlterField(
            model_name="articlecomptevente",
            name="code_analytique",
            field=models.ForeignKey(
                blank=True,
                help_text="Prioritaire sur le code analytique du poste de gestion, s'il y en a un.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.codeanalytique",
                verbose_name="code analytique par défaut",
            ),
        ),
        migrations.AlterField(
            model_name="articlecomptevente",
            name="compte_vente",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisé seulement si aucun poste de gestion n'est renseigné ci-dessus.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte de vente (fixe)",
            ),
        ),
        migrations.CreateModel(
            name="PosteGestion",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "groupe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Achats"),
                            ("VE", "Ventes"),
                            ("OP", "Opérations"),
                            ("ST", "Sous-traitance"),
                        ],
                        help_text="Tag informatif hérité de la source — n'importe quel poste peut porter un mapping achat et/ou vente quel que soit son groupe.",
                        max_length=5,
                        verbose_name="groupe",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "code_analytique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.codeanalytique",
                        verbose_name="code analytique par défaut",
                    ),
                ),
                (
                    "compte_achat_france",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte d'achat — France",
                    ),
                ),
                (
                    "compte_achat_france_exonere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte d'achat — France exonérée de TVA",
                    ),
                ),
                (
                    "compte_achat_hors_ue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte d'achat — hors UE",
                    ),
                ),
                (
                    "compte_achat_intra_ue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte d'achat — intracommunautaire",
                    ),
                ),
                (
                    "compte_vente_france",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente — France",
                    ),
                ),
                (
                    "compte_vente_france_exonere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente — France exonérée de TVA",
                    ),
                ),
                (
                    "compte_vente_hors_ue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente — hors UE",
                    ),
                ),
                (
                    "compte_vente_intra_ue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente — intracommunautaire",
                    ),
                ),
                (
                    "compte_vente_tva_majoree",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cas particulier hérité de la source, indépendant du régime fiscal — non résolu automatiquement, à sélectionner manuellement si besoin.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte de vente — TVA majorée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste de gestion",
                "verbose_name_plural": "Postes de gestion",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="articlecompteachat",
            name="poste_gestion",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, prioritaire sur le compte d'achat fixe ci-dessous : le compte est résolu selon le régime fiscal du fournisseur.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.postegestion",
                verbose_name="poste de gestion",
            ),
        ),
        migrations.AddField(
            model_name="articlecomptevente",
            name="poste_gestion",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, prioritaire sur le compte de vente fixe ci-dessous : le compte est résolu selon le régime fiscal du client.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.postegestion",
                verbose_name="poste de gestion",
            ),
        ),
    ]
