# Generated by Django 5.2.17 on 2026-09-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0010_conditionpaiement_pays_remove_contact_telephone_and_more"),
        ("comptabilite", "0007_alter_articlecompteachat_code_analytique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiersCompteComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compte_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. sous-compte de 411",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte client",
                    ),
                ),
                (
                    "compte_fournisseur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ex. sous-compte de 401",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="compte fournisseur",
                    ),
                ),
                (
                    "tiers",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptes_comptables",
                        to="commercial.tiers",
                        verbose_name="tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptable de tiers",
                "verbose_name_plural": "Comptes comptables de tiers",
                "ordering": ["tiers"],
            },
        ),
    ]
