# Generated by Django 5.2.17 on 2026-09-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0008_tierscomptecomptable"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierscomptecomptable",
            name="code_client",
            field=models.CharField(
                blank=True,
                help_text='5 lettres, ex. "DUPON" — génère automatiquement le compte 411 + ces lettres',
                max_length=5,
                verbose_name="code client (5 lettres)",
            ),
        ),
        migrations.AddField(
            model_name="tierscomptecomptable",
            name="code_fournisseur",
            field=models.CharField(
                blank=True,
                help_text='5 lettres, ex. "DUPON" — génère automatiquement le compte 401 + ces lettres',
                max_length=5,
                verbose_name="code fournisseur (5 lettres)",
            ),
        ),
        migrations.AlterField(
            model_name="tierscomptecomptable",
            name="compte_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. sous-compte de 411 — rempli automatiquement si un code client est renseigné",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte client",
            ),
        ),
        migrations.AlterField(
            model_name="tierscomptecomptable",
            name="compte_fournisseur",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. sous-compte de 401 — rempli automatiquement si un code fournisseur est renseigné",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte fournisseur",
            ),
        ),
    ]
