# Generated by Django 5.2.17 on 2026-09-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_lignecommandefournisseur_taux_tva_facturefournisseur"),
        ("comptabilite", "0009_tierscomptecomptable_code_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecriturecomptable",
            name="facture_fournisseur",
            field=models.OneToOneField(
                blank=True,
                help_text="Renseigné automatiquement pour une écriture générée depuis une facture fournisseur (empêche sa double génération). Référencé par nom d'app (« achats.FactureFournisseur ») plutôt qu'importé : achats importe déjà comptabilite.models, un import direct créerait un cycle.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecriture_comptable",
                to="achats.facturefournisseur",
                verbose_name="facture fournisseur d'origine",
            ),
        ),
        migrations.AddField(
            model_name="parametrescomptables",
            name="compte_achat_defaut",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. 601 — Achats stockés de matières premières",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte d'achat par défaut",
            ),
        ),
        migrations.AddField(
            model_name="parametrescomptables",
            name="compte_fournisseur_defaut",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. 401 — Fournisseurs",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte fournisseur par défaut",
            ),
        ),
        migrations.AddField(
            model_name="parametrescomptables",
            name="compte_tva_deductible_defaut",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. 44566 — TVA déductible sur autres biens et services",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte de TVA déductible par défaut",
            ),
        ),
        migrations.AddField(
            model_name="parametrescomptables",
            name="journal_achats",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.journalcomptable",
                verbose_name="journal des achats",
            ),
        ),
    ]
