# Generated by Django 5.2.17 on 2026-09-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0011_seed_parametres_achats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tierscomptecomptable",
            name="code_client",
            field=models.CharField(
                blank=True,
                help_text='5 lettres et/ou chiffres, ex. "DUP01" — génère automatiquement le compte 411 + ce code',
                max_length=5,
                verbose_name="code client (5 caractères)",
            ),
        ),
        migrations.AlterField(
            model_name="tierscomptecomptable",
            name="code_fournisseur",
            field=models.CharField(
                blank=True,
                help_text='5 lettres et/ou chiffres, ex. "DUP01" — génère automatiquement le compte 401 + ce code',
                max_length=5,
                verbose_name="code fournisseur (5 caractères)",
            ),
        ),
    ]
