# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0012_alter_tierscomptecomptable_code_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ligneecriture",
            name="credit",
            field=comptes.champs.ChampDecimal(
                decimal_places=2, default=0, max_digits=14, verbose_name="crédit"
            ),
        ),
        migrations.AlterField(
            model_name="ligneecriture",
            name="debit",
            field=comptes.champs.ChampDecimal(
                decimal_places=2, default=0, max_digits=14, verbose_name="débit"
            ),
        ),
    ]
