# Generated by Django 5.2.17 on 2026-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0013_passage_en_decimal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresExportComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_journal_ventes",
                    models.CharField(
                        default="VT",
                        max_length=2,
                        verbose_name="code du journal des ventes",
                    ),
                ),
                (
                    "code_journal_achats",
                    models.CharField(
                        default="AC",
                        max_length=2,
                        verbose_name="code du journal des achats",
                    ),
                ),
                (
                    "code_journal_banque",
                    models.CharField(
                        default="B2",
                        max_length=2,
                        verbose_name="code du journal de banque",
                    ),
                ),
                (
                    "compte_banque",
                    models.CharField(
                        default="512100",
                        help_text="Compte débité à l'encaissement d'une facture client, crédité au règlement d'un fournisseur.",
                        max_length=8,
                        verbose_name="compte de banque",
                    ),
                ),
                (
                    "libelle_ventes",
                    models.CharField(
                        default="code_facture,nom_tiers",
                        help_text="Éléments séparés par une virgule parmi : code_facture, nom_tiers, reference_fournisseur (30 caractères au plus au total).",
                        max_length=100,
                        verbose_name="libellé des écritures de ventes",
                    ),
                ),
                (
                    "libelle_achats",
                    models.CharField(
                        default="code_facture,nom_tiers",
                        max_length=100,
                        verbose_name="libellé des écritures d'achats",
                    ),
                ),
                (
                    "libelle_banque",
                    models.CharField(
                        default="nom_tiers",
                        max_length=100,
                        verbose_name="libellé des écritures de banque",
                    ),
                ),
                (
                    "piece_achats",
                    models.CharField(
                        choices=[
                            ("code_facture", "Code facture"),
                            ("reference_fournisseur", "Référence fournisseur"),
                        ],
                        default="code_facture",
                        help_text="Ce qui est écrit dans la colonne « pièce » des écritures d'achats ; la référence fournisseur est toujours reprise dans sa propre colonne.",
                        max_length=30,
                        verbose_name="référence de pièce des achats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de l'export comptable",
                "verbose_name_plural": "Paramètres de l'export comptable",
            },
        ),
    ]
