# Generated by Django 5.2.17 on 2026-10-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0014_parametresexportcomptable"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrescomptables",
            name="compte_tva_autoliquidation_deductible",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. 445663. Vide : ce compte est créé au premier achat en autoliquidation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte de TVA déductible sur autoliquidation",
            ),
        ),
        migrations.AddField(
            model_name="parametrescomptables",
            name="compte_tva_autoliquidation_due",
            field=models.ForeignKey(
                blank=True,
                help_text="Ex. 445200 (TVA due intracommunautaire). Vide : ce compte est créé au premier achat en autoliquidation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="comptabilite.comptecomptable",
                verbose_name="compte de TVA due sur autoliquidation",
            ),
        ),
    ]
