# Generated by Django 5.2.17 on 2026-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvenementConnexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="identifiant saisi"
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("succes", "Connexion réussie"),
                            ("echec", "Échec d'authentification"),
                            ("bloque", "Refusée : compte verrouillé"),
                            ("deblocage", "Déblocage manuel"),
                        ],
                        max_length=12,
                        verbose_name="événement",
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Indicative : derrière un reverse proxy, c'est l'adresse transmise par celui-ci.",
                        null=True,
                        verbose_name="adresse IP",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de connexion",
                "verbose_name_plural": "Journal des connexions",
                "ordering": ["-date", "-id"],
                "permissions": [
                    (
                        "debloquer_compte",
                        "Peut débloquer un compte verrouillé après trop d'échecs",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["identifiant", "date"],
                        name="comptes_eve_identif_496f41_idx",
                    )
                ],
            },
        ),
    ]
