# Generated by Django 5.2.17 on 2026-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0001_journal_connexions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Societe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        default="Mon entreprise",
                        max_length=200,
                        verbose_name="raison sociale",
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        help_text="Ex. SAS, SARL, EURL",
                        max_length=50,
                        verbose_name="forme juridique",
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="code postal"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "site_web",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="site web"
                    ),
                ),
                (
                    "siret",
                    models.CharField(blank=True, max_length=20, verbose_name="SIRET"),
                ),
                (
                    "tva_intracommunautaire",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="TVA intracommunautaire"
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True,
                        help_text="Ex. 10 000 €",
                        max_length=50,
                        verbose_name="capital social",
                    ),
                ),
                (
                    "rcs",
                    models.CharField(
                        blank=True,
                        help_text="Ex. RCS Lyon 123 456 789",
                        max_length=100,
                        verbose_name="RCS",
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=40, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=15, verbose_name="BIC"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Affiché en en-tête des documents (PNG ou JPEG).",
                        upload_to="societe/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "mentions_devis",
                    models.TextField(
                        blank=True,
                        help_text="Conditions de vente, pénalités de retard, etc., imprimées en bas du devis.",
                        verbose_name="mentions sur les devis",
                    ),
                ),
                (
                    "mentions_livraison",
                    models.TextField(
                        blank=True, verbose_name="mentions sur les bons de livraison"
                    ),
                ),
            ],
            options={
                "verbose_name": "Société",
                "verbose_name_plural": "Société",
            },
        ),
    ]
