# Generated by Django 5.2.17 on 2026-10-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_societe"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="mentions_commande",
            field=models.TextField(
                blank=True,
                help_text="Ex. conditions générales de vente, réserve de propriété.",
                verbose_name="mentions sur les accusés de réception de commande",
            ),
        ),
    ]
