# Generated by Django 5.2.17 on 2026-10-05 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0003_mentions_commande"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceColonnes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecran", models.CharField(max_length=150, verbose_name="écran")),
                (
                    "masquees",
                    models.JSONField(
                        blank=True, default=list, verbose_name="colonnes masquées"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_colonnes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de colonnes",
                "verbose_name_plural": "Préférences de colonnes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("utilisateur", "ecran"),
                        name="unique_preference_colonnes",
                    )
                ],
            },
        ),
    ]
