# Generated by Django 5.2.17 on 2026-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0004_preferences_colonnes"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="mentions_facture",
            field=models.TextField(
                blank=True,
                help_text="Escompte, pénalités de retard et indemnité forfaitaire de recouvrement (40 €), imprimés en bas des factures. Vide : texte légal par défaut (pas d'escompte, pénalités de 3 fois le taux d'intérêt légal, 40 €).",
                verbose_name="mentions sur les factures",
            ),
        ),
    ]
