# Generated by Django 5.2.17 on 2026-10-10 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0005_societe_mentions_facture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="date")),
                (
                    "modele",
                    models.CharField(
                        help_text="Étiquette Django du modèle modifié (app.Modele)",
                        max_length=80,
                        verbose_name="modèle",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "modifications",
                    models.JSONField(
                        default=list,
                        help_text="[{pk, avant: {champ: valeur}, apres: {champ: valeur}}]",
                        verbose_name="modifications",
                    ),
                ),
                (
                    "crees",
                    models.JSONField(
                        default=list,
                        help_text="[[étiquette du modèle, clé]]",
                        verbose_name="objets créés",
                    ),
                ),
                (
                    "annule_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="annulé le"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de modifications",
                "verbose_name_plural": "Lots de modifications",
                "ordering": ["-date"],
            },
        ),
    ]
