# Generated by Django 5.2.17 on 2026-08-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chiffrage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("reference_tiime", models.CharField(blank=True, max_length=100)),
                ("montant_ht", models.FloatField(blank=True, null=True)),
                ("montant_ttc", models.FloatField(blank=True, null=True)),
                ("date_facturation", models.DateField()),
                ("statut_paiement", models.CharField(blank=True, max_length=50)),
                (
                    "mode_creation",
                    models.CharField(
                        choices=[("manuel", "Manuel"), ("automatique", "Automatique")],
                        default="manuel",
                        max_length=20,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="chiffrage.commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-date_facturation", "numero"],
            },
        ),
    ]
