# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0002_alter_commande_adresse_facturation_and_more"),
        ("facturation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures",
                to="chiffrage.commande",
                verbose_name="commande",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="date_facturation",
            field=models.DateField(verbose_name="date de facturation"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_creation",
            field=models.CharField(
                choices=[("manuel", "Manuel"), ("automatique", "Automatique")],
                default="manuel",
                max_length=20,
                verbose_name="mode de création",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ht",
            field=models.FloatField(blank=True, null=True, verbose_name="montant HT"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ttc",
            field=models.FloatField(blank=True, null=True, verbose_name="montant TTC"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="reference_tiime",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="référence Tiime"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="statut_paiement",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="statut de paiement"
            ),
        ),
    ]
