# Generated by Django 5.2.17 on 2026-10-03 07:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def normaliser_vers(texte):
    """« payé/réglé/soldé » → payée, « partiel » → partiellement payée, le reste
    (dont le vide, « impayé », « non payé ») → à payer."""
    texte = (texte or "").strip().lower()
    if "partiel" in texte:
        return "partiel"
    if any(mot in texte for mot in ("pay", "régl", "regl", "sold")) and "impay" not in texte and "non" not in texte:
        return "paye"
    return "a_payer"


def normaliser_statuts_paiement(apps, schema_editor):
    """Le statut de paiement était un texte libre (souvent vide) : on le ramène aux
    trois valeurs de l'énumérateur."""
    Facture = apps.get_model("facturation", "Facture")
    for facture in Facture.objects.all():
        Facture.objects.filter(pk=facture.pk).update(statut_paiement=normaliser_vers(facture.statut_paiement))


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0017_permissions_metier"),
        ("facturation", "0002_alter_facture_commande_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="date_paiement",
            field=models.DateField(
                blank=True,
                help_text="Date du dernier règlement ; posée automatiquement au passage à « Payée ».",
                null=True,
                verbose_name="date de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ht",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ttc",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="montant TTC",
            ),
        ),
        migrations.RunPython(normaliser_statuts_paiement, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="facture",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("a_payer", "À payer"),
                    ("partiel", "Partiellement payée"),
                    ("paye", "Payée"),
                ],
                default="a_payer",
                max_length=20,
                verbose_name="statut de paiement",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalFacture",
            fields=[
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="numéro"
                    ),
                ),
                (
                    "reference_tiime",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="référence Tiime"
                    ),
                ),
                (
                    "montant_ht",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="montant HT",
                    ),
                ),
                (
                    "montant_ttc",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="montant TTC",
                    ),
                ),
                (
                    "date_facturation",
                    models.DateField(verbose_name="date de facturation"),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("a_payer", "À payer"),
                            ("partiel", "Partiellement payée"),
                            ("paye", "Payée"),
                        ],
                        default="a_payer",
                        max_length=20,
                        verbose_name="statut de paiement",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True,
                        help_text="Date du dernier règlement ; posée automatiquement au passage à « Payée ».",
                        null=True,
                        verbose_name="date de paiement",
                    ),
                ),
                (
                    "mode_creation",
                    models.CharField(
                        choices=[("manuel", "Manuel"), ("automatique", "Automatique")],
                        default="manuel",
                        max_length=20,
                        verbose_name="mode de création",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="chiffrage.commande",
                        verbose_name="commande",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Facture",
                "verbose_name_plural": "historical Factures",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
