# Generated by Django 5.2.17 on 2026-10-03 07:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0018_livraison_annulable"),
        ("facturation", "0003_verrou_paiement_historique"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="anticipee",
            field=models.BooleanField(
                default=False,
                help_text="Cochez pour facturer avant livraison (acompte, facturation à la commande) : lève la limite « pas plus que le livré ».",
                verbose_name="facturation anticipée",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="facture_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour un avoir : la facture qu'il corrige (obligatoire).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avoirs",
                to="facturation.facture",
                verbose_name="facture d'origine",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="motif",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire pour un avoir.",
                max_length=200,
                verbose_name="motif",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="type_document",
            field=models.CharField(
                choices=[("facture", "Facture"), ("avoir", "Avoir")],
                default="facture",
                max_length=10,
                verbose_name="type de document",
            ),
        ),
        migrations.AddField(
            model_name="historicalfacture",
            name="anticipee",
            field=models.BooleanField(
                default=False,
                help_text="Cochez pour facturer avant livraison (acompte, facturation à la commande) : lève la limite « pas plus que le livré ».",
                verbose_name="facturation anticipée",
            ),
        ),
        migrations.AddField(
            model_name="historicalfacture",
            name="facture_origine",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Pour un avoir : la facture qu'il corrige (obligatoire).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="facturation.facture",
                verbose_name="facture d'origine",
            ),
        ),
        migrations.AddField(
            model_name="historicalfacture",
            name="motif",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire pour un avoir.",
                max_length=200,
                verbose_name="motif",
            ),
        ),
        migrations.AddField(
            model_name="historicalfacture",
            name="type_document",
            field=models.CharField(
                choices=[("facture", "Facture"), ("avoir", "Avoir")],
                default="facture",
                max_length=10,
                verbose_name="type de document",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ht",
            field=models.FloatField(
                blank=True,
                help_text="Négatif pour un avoir.",
                null=True,
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ttc",
            field=models.FloatField(
                blank=True,
                help_text="Négatif pour un avoir.",
                null=True,
                verbose_name="montant TTC",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacture",
            name="montant_ht",
            field=models.FloatField(
                blank=True,
                help_text="Négatif pour un avoir.",
                null=True,
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacture",
            name="montant_ttc",
            field=models.FloatField(
                blank=True,
                help_text="Négatif pour un avoir.",
                null=True,
                verbose_name="montant TTC",
            ),
        ),
        migrations.CreateModel(
            name="FactureLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "prix_unitaire_ht",
                    models.FloatField(
                        blank=True,
                        help_text="Repris de la ligne de commande si laissé vide.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="prix unitaire HT",
                    ),
                ),
                (
                    "taux_tva",
                    models.FloatField(
                        blank=True,
                        help_text="Repris de la ligne de commande si laissé vide.",
                        null=True,
                        verbose_name="taux de TVA (%)",
                    ),
                ),
                (
                    "commande_ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_facture",
                        to="chiffrage.commandeligne",
                        verbose_name="ligne de commande",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="facturation.facture",
                        verbose_name="facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture",
                "verbose_name_plural": "Lignes de facture",
                "ordering": ["facture", "id"],
            },
        ),
    ]
