# Generated by Django 5.2.17 on 2026-10-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturation", "0004_lignes_avoirs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facture",
            options={
                "ordering": ["-date_facturation", "numero"],
                "permissions": [
                    ("creer_avoir", "Peut créer un avoir"),
                    (
                        "facturer_avant_livraison",
                        "Peut faire une facturation anticipée (avant livraison)",
                    ),
                ],
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
    ]
