# Generated by Django 5.2.17 on 2026-10-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturation", "0005_perms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facture",
            options={
                "ordering": ["-date_facturation", "numero"],
                "permissions": [
                    ("relancer_facture", "Peut envoyer une relance de paiement"),
                    ("creer_avoir", "Peut créer un avoir"),
                    (
                        "facturer_avant_livraison",
                        "Peut faire une facturation anticipée (avant livraison)",
                    ),
                ],
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.CreateModel(
            name="RelanceFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.PositiveSmallIntegerField(
                        help_text="1 rappel, 2 relance, 3 dernière relance",
                        verbose_name="niveau",
                    ),
                ),
                (
                    "destinataire",
                    models.EmailField(max_length=254, verbose_name="destinataire"),
                ),
                ("objet", models.CharField(max_length=200, verbose_name="objet")),
                ("corps", models.TextField(verbose_name="message")),
                ("envoyee", models.BooleanField(default=True, verbose_name="envoyée")),
                (
                    "erreur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="erreur d'envoi"
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="facturation.facture",
                        verbose_name="facture",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_envoyees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="envoyée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance de paiement",
                "verbose_name_plural": "Relances de paiement",
                "ordering": ["-date_envoi", "-id"],
            },
        ),
    ]
