# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturation", "0006_relances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="montant_ht",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Négatif pour un avoir.",
                max_digits=14,
                null=True,
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_ttc",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Négatif pour un avoir.",
                max_digits=14,
                null=True,
                verbose_name="montant TTC",
            ),
        ),
        migrations.AlterField(
            model_name="factureligne",
            name="prix_unitaire_ht",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=6,
                help_text="Repris de la ligne de commande si laissé vide.",
                max_digits=16,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix unitaire HT",
            ),
        ),
        migrations.AlterField(
            model_name="factureligne",
            name="taux_tva",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Repris de la ligne de commande si laissé vide.",
                max_digits=7,
                null=True,
                verbose_name="taux de TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacture",
            name="montant_ht",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Négatif pour un avoir.",
                max_digits=14,
                null=True,
                verbose_name="montant HT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfacture",
            name="montant_ttc",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Négatif pour un avoir.",
                max_digits=14,
                null=True,
                verbose_name="montant TTC",
            ),
        ),
    ]
