# Generated by Django 5.2.17 on 2026-08-31 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commercial", "0001_initial"),
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_creation", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "taux_marge_globale",
                    models.FloatField(
                        blank=True,
                        help_text="Optionnel, écrase les marges par défaut",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis",
                        to="commercial.tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-date_creation", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_commande", models.DateField()),
                ("statut", models.CharField(blank=True, max_length=50)),
                (
                    "adresse_facturation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_facturation",
                        to="commercial.adresse",
                    ),
                ),
                (
                    "adresse_livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_livraison",
                        to="commercial.adresse",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="chiffrage.devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-date_commande", "numero"],
            },
        ),
        migrations.CreateModel(
            name="DevisLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.FloatField()),
                (
                    "cout_matiere_calcule",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "taux_marge_matiere_applique",
                    models.FloatField(
                        blank=True,
                        help_text="Pré-rempli depuis l'article, éditable",
                        null=True,
                    ),
                ),
                (
                    "prix_vente_matiere",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis_lignes",
                        to="technique.article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="chiffrage.devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de devis",
                "verbose_name_plural": "Lignes de devis",
                "ordering": ["devis", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrdreFabrication",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("quantite", models.FloatField()),
                ("date_lancement", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        blank=True, help_text="Statut de production", max_length=50
                    ),
                ),
                (
                    "statut_synchro",
                    models.CharField(
                        choices=[
                            ("synchronise", "Synchronisé"),
                            ("en_attente", "En attente"),
                            ("echec_persistant", "Échec persistant"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("nombre_tentatives", models.PositiveIntegerField(default=0)),
                ("date_derniere_tentative", models.DateField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordres_fabrication",
                        to="technique.article",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres_fabrication",
                        to="chiffrage.commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre de fabrication",
                "verbose_name_plural": "Ordres de fabrication",
                "ordering": ["-date_lancement", "numero"],
            },
        ),
        migrations.CreateModel(
            name="DevisLigneOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField()),
                (
                    "cout_calcule",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "taux_marge_applique",
                    models.FloatField(
                        blank=True,
                        help_text="Pré-rempli depuis le poste, éditable",
                        null=True,
                    ),
                ),
                (
                    "prix_vente",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "devis_ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="chiffrage.devisligne",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis_operations",
                        to="technique.postetravail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération de ligne de devis",
                "verbose_name_plural": "Opérations de ligne de devis",
                "ordering": ["devis_ligne", "ordre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("devis_ligne", "ordre"),
                        name="unique_ordre_par_ligne_devis",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField()),
                (
                    "temps_prevu",
                    models.FloatField(
                        blank=True,
                        help_text="Copié de la gamme au lancement",
                        null=True,
                    ),
                ),
                (
                    "temps_reel",
                    models.FloatField(
                        blank=True,
                        help_text="Alimenté par le planning atelier",
                        null=True,
                    ),
                ),
                (
                    "quantite_bonne",
                    models.FloatField(
                        blank=True,
                        help_text="Alimenté par le planning atelier",
                        null=True,
                    ),
                ),
                (
                    "quantite_rebut",
                    models.FloatField(
                        blank=True,
                        help_text="Alimenté par le planning atelier",
                        null=True,
                    ),
                ),
                ("statut", models.CharField(blank=True, max_length=50)),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_of",
                        to="technique.postetravail",
                    ),
                ),
                (
                    "ordre_fabrication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="chiffrage.ordrefabrication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération d'ordre de fabrication",
                "verbose_name_plural": "Opérations d'ordre de fabrication",
                "ordering": ["ordre_fabrication", "ordre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ordre_fabrication", "ordre"),
                        name="unique_ordre_par_of",
                    )
                ],
            },
        ),
    ]
