# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0001_initial"),
        ("commercial", "0003_alter_adresse_adresse_alter_adresse_code_postal_and_more"),
        (
            "technique",
            "0002_alter_article_cout_unitaire_alter_article_epaisseur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="adresse_facturation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes_facturation",
                to="commercial.adresse",
                verbose_name="adresse de facturation",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="adresse_livraison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes_livraison",
                to="commercial.adresse",
                verbose_name="adresse de livraison",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateField(verbose_name="date de commande"),
        ),
        migrations.AlterField(
            model_name="commande",
            name="devis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes",
                to="chiffrage.devis",
                verbose_name="devis",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(blank=True, max_length=50, verbose_name="statut"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis",
                to="commercial.tiers",
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="date_creation",
            field=models.DateField(verbose_name="date de création"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="statut",
            field=models.CharField(
                choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                default="brouillon",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="taux_marge_globale",
            field=models.FloatField(
                blank=True,
                help_text="Optionnel, écrase les marges par défaut",
                null=True,
                verbose_name="taux de marge globale",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis_lignes",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="cout_matiere_calcule",
            field=models.FloatField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="coût matière calculé",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="devis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="chiffrage.devis",
                verbose_name="devis",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_matiere",
            field=models.FloatField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="prix de vente matière",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="quantite",
            field=models.FloatField(verbose_name="quantité"),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="taux_marge_matiere_applique",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis l'article, éditable",
                null=True,
                verbose_name="taux de marge matière appliqué",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="cout_calcule",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="coût calculé"
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="devis_ligne",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="chiffrage.devisligne",
                verbose_name="ligne de devis",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="ordre",
            field=models.PositiveIntegerField(verbose_name="ordre"),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis_operations",
                to="technique.postetravail",
                verbose_name="poste",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="prix_vente",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="prix de vente"
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="taux_marge_applique",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis le poste, éditable",
                null=True,
                verbose_name="taux de marge appliqué",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="ordre",
            field=models.PositiveIntegerField(verbose_name="ordre"),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="ordre_fabrication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="chiffrage.ordrefabrication",
                verbose_name="ordre de fabrication",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_of",
                to="technique.postetravail",
                verbose_name="poste",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="quantite_bonne",
            field=models.FloatField(
                blank=True,
                help_text="Alimenté par le planning atelier",
                null=True,
                verbose_name="quantité bonne",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="quantite_rebut",
            field=models.FloatField(
                blank=True,
                help_text="Alimenté par le planning atelier",
                null=True,
                verbose_name="quantité rebut",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="statut",
            field=models.CharField(blank=True, max_length=50, verbose_name="statut"),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="temps_prevu",
            field=models.FloatField(
                blank=True,
                help_text="Copié de la gamme au lancement",
                null=True,
                verbose_name="temps prévu",
            ),
        ),
        migrations.AlterField(
            model_name="operationof",
            name="temps_reel",
            field=models.FloatField(
                blank=True,
                help_text="Alimenté par le planning atelier",
                null=True,
                verbose_name="temps réel",
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordres_fabrication",
                to="technique.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordres_fabrication",
                to="chiffrage.commande",
                verbose_name="commande",
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="date_derniere_tentative",
            field=models.DateField(
                blank=True, null=True, verbose_name="date de dernière tentative"
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="date_lancement",
            field=models.DateField(verbose_name="date de lancement"),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="nombre_tentatives",
            field=models.PositiveIntegerField(
                default=0, verbose_name="nombre de tentatives"
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="numero",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="numéro"
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="quantite",
            field=models.FloatField(verbose_name="quantité"),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="statut",
            field=models.CharField(
                blank=True,
                help_text="Statut de production",
                max_length=50,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="ordrefabrication",
            name="statut_synchro",
            field=models.CharField(
                choices=[
                    ("synchronise", "Synchronisé"),
                    ("en_attente", "En attente"),
                    ("echec_persistant", "Échec persistant"),
                ],
                default="en_attente",
                max_length=20,
                verbose_name="statut de synchronisation",
            ),
        ),
    ]
