# Generated by Django 5.2.17 on 2026-09-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0002_alter_commande_adresse_facturation_and_more"),
        ("commercial", "0003_alter_adresse_adresse_alter_adresse_code_postal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="adresse_facturation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis_facturation",
                to="commercial.adresse",
                verbose_name="adresse de facturation",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="adresse_livraison",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis_livraison",
                to="commercial.adresse",
                verbose_name="adresse de livraison",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis",
                to="commercial.contact",
                verbose_name="contact",
            ),
        ),
    ]
