# Generated by Django 5.2.17 on 2026-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chiffrage",
            "0003_devis_adresse_facturation_devis_adresse_livraison_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="devisligne",
            name="prix_vente_unitaire_force",
            field=models.FloatField(
                blank=True,
                help_text="Si renseigné, remplace le calcul automatique (coût matière × marge) : prix de vente matière de la ligne = quantité × ce prix unitaire.",
                null=True,
                verbose_name="prix de vente unitaire forcé (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_matiere",
            field=models.FloatField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="prix de vente matière (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="prix_vente",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="prix de vente (HT)"
            ),
        ),
    ]
