# Generated by Django 5.2.17 on 2026-09-02 11:34

import chiffrage.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0004_devisligne_prix_vente_unitaire_force_and_more"),
        ("commercial", "0004_tauxtva"),
    ]

    operations = [
        migrations.AddField(
            model_name="devisligne",
            name="taux_tva",
            field=models.ForeignKey(
                blank=True,
                default=chiffrage.models._taux_tva_par_defaut,
                help_text="Pré-rempli avec le taux par défaut du référentiel, modifiable par ligne",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis_lignes",
                to="commercial.tauxtva",
                verbose_name="taux de TVA",
            ),
        ),
    ]
