# Generated by Django 5.2.17 on 2026-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0005_devisligne_taux_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="delai",
            field=models.CharField(
                blank=True,
                help_text="Délai de livraison annoncé. Texte libre : des suggestions viennent du référentiel « Délais proposés » (commercial.DelaiPropose), mais toute valeur saisie est acceptée.",
                max_length=100,
                verbose_name="délai",
            ),
        ),
    ]
