# Generated by Django 5.2.17 on 2026-09-02 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0006_devis_delai"),
        ("technique", "0003_article_libelle"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_commandee",
                    models.FloatField(verbose_name="quantité commandée"),
                ),
                (
                    "quantite_livree",
                    models.FloatField(
                        default=0,
                        editable=False,
                        help_text="Cumul recalculé depuis les livraisons",
                        verbose_name="quantité livrée",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_commande",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="chiffrage.commande",
                        verbose_name="commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
                "ordering": ["commande", "id"],
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="numéro",
                    ),
                ),
                (
                    "date_livraison",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date de livraison",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livraisons",
                        to="chiffrage.commande",
                        verbose_name="commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "ordering": ["-date_livraison", "numero"],
            },
        ),
        migrations.CreateModel(
            name="LivraisonLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_livree", models.FloatField(verbose_name="quantité livrée")),
                (
                    "commande_ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livraisons_lignes",
                        to="chiffrage.commandeligne",
                        verbose_name="ligne de commande",
                    ),
                ),
                (
                    "livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="chiffrage.livraison",
                        verbose_name="livraison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de livraison",
                "verbose_name_plural": "Lignes de livraison",
                "ordering": ["livraison", "id"],
            },
        ),
    ]
