# Generated by Django 5.2.17 on 2026-09-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0007_commandeligne_livraison_livraisonligne"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandeligne",
            name="date_livraison_prevue",
            field=models.DateField(
                blank=True,
                help_text="Peut différer d'une ligne à l'autre au sein d'une même commande.",
                null=True,
                verbose_name="date de livraison prévue",
            ),
        ),
        migrations.AddField(
            model_name="commandeligne",
            name="devis_ligne",
            field=models.ForeignKey(
                blank=True,
                help_text="Sert uniquement à retrouver prix et taux de TVA sans les dupliquer (voir prix_vente_unitaire/taux_tva/montant_ht/montant_ttc) — jamais montré tel quel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande",
                to="chiffrage.devisligne",
                verbose_name="ligne de devis d'origine",
            ),
        ),
    ]
