# Generated by Django 5.2.17 on 2026-09-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0009_synchroniser_lignes_commande_existantes"),
        ("commercial", "0008_delaipropose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commandeligne",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="Libellé propre à cette commande, remplace celui de l'article s'il est renseigné.",
                max_length=255,
                verbose_name="désignation",
            ),
        ),
        migrations.AddField(
            model_name="commandeligne",
            name="prix_vente_unitaire",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis le devis à la création de la commande, modifiable ensuite.",
                null=True,
                verbose_name="prix de vente unitaire (HT)",
            ),
        ),
        migrations.AddField(
            model_name="commandeligne",
            name="taux_tva",
            field=models.ForeignKey(
                blank=True,
                help_text="Pré-rempli depuis le devis à la création de la commande, modifiable ensuite.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande",
                to="commercial.tauxtva",
                verbose_name="taux de TVA",
            ),
        ),
        migrations.AlterField(
            model_name="commandeligne",
            name="devis_ligne",
            field=models.ForeignKey(
                blank=True,
                help_text="Ligne de devis servie de valeur de départ pour les surcharges ci-dessous (jamais modifiée elle-même) — vide pour une ligne ajoutée directement sur la commande, sans devis correspondant.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande",
                to="chiffrage.devisligne",
                verbose_name="ligne de devis d'origine",
            ),
        ),
        migrations.CreateModel(
            name="CommandeLigneModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "champ",
                    models.CharField(max_length=50, verbose_name="champ modifié"),
                ),
                (
                    "ancienne_valeur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ancienne valeur"
                    ),
                ),
                (
                    "nouvelle_valeur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nouvelle valeur"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "commande_ligne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="chiffrage.commandeligne",
                        verbose_name="ligne de commande",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifications_lignes_commande",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modification de ligne de commande",
                "verbose_name_plural": "Modifications de ligne de commande",
                "ordering": ["-date_modification"],
            },
        ),
    ]
