# Generated by Django 5.2.17 on 2026-09-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0011_backfill_prix_taux_lignes_commande"),
        ("commercial", "0012_devise_tiers_bic_tiers_iban_tiers_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="devise",
            field=models.ForeignKey(
                blank=True,
                help_text="Par défaut celle du client si renseignée",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes",
                to="commercial.devise",
                verbose_name="devise",
            ),
        ),
    ]
