# Generated by Django 5.2.17 on 2026-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0012_commande_devise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devisligne",
            options={
                "ordering": ["devis", "ordre", "id"],
                "verbose_name": "Ligne de devis",
                "verbose_name_plural": "Lignes de devis",
            },
        ),
        migrations.AddField(
            model_name="devisligne",
            name="ordre",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d'affichage (glisser-déposer sur la fiche devis) — repris tel quel sur la commande.",
                verbose_name="ordre",
            ),
        ),
    ]
