# Generated by Django 5.2.17 on 2026-10-02 18:47

import chiffrage.models
import django.core.validators
from django.db import migrations, models


def normaliser_statuts_commande(apps, schema_editor):
    """Le statut de commande était un texte libre (le plus souvent vide) : on le
    ramène aux trois valeurs du nouvel énumérateur. « Soldée » si la commande a
    des lignes et qu'elles sont toutes entièrement livrées, sinon « En cours »."""
    Commande = apps.get_model("chiffrage", "Commande")
    CommandeLigne = apps.get_model("chiffrage", "CommandeLigne")
    for commande in Commande.objects.all():
        lignes = list(CommandeLigne.objects.filter(commande=commande))
        soldee = bool(lignes) and all(
            ligne.quantite_commandee - ligne.quantite_livree <= 0 for ligne in lignes
        )
        Commande.objects.filter(pk=commande.pk).update(statut="soldee" if soldee else "en_cours")


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0014_commande_devis_facultatif_client_reference"),
    ]

    operations = [
        migrations.RunPython(normaliser_statuts_commande, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("soldee", "Soldée"),
                    ("annulee", "Annulée"),
                ],
                default="en_cours",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="commandeligne",
            name="prix_vente_unitaire",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis le devis à la création de la commande, modifiable ensuite.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix de vente unitaire (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="commandeligne",
            name="quantite_commandee",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="quantité commandée",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="taux_marge_globale",
            field=models.FloatField(
                blank=True,
                help_text="Optionnel, écrase les marges par défaut",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge globale",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_unitaire_force",
            field=models.FloatField(
                blank=True,
                help_text="Si renseigné, remplace le calcul automatique (coût matière × marge) : prix de vente matière de la ligne = quantité × ce prix unitaire.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix de vente unitaire forcé (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="quantite",
            field=models.FloatField(
                validators=[chiffrage.models._strictement_positif],
                verbose_name="quantité",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="taux_marge_matiere_applique",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis l'article, éditable",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge matière appliqué",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="taux_marge_applique",
            field=models.FloatField(
                blank=True,
                help_text="Pré-rempli depuis le poste, éditable",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge appliqué",
            ),
        ),
    ]
