# Generated by Django 5.2.17 on 2026-10-02 19:01

import chiffrage.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0015_integrite_validations_statut_commande"),
        ("commercial", "0018_seed_taux_tva_zero"),
        ("technique", "0005_article_taux_tva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCommande",
            fields=[
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="numéro"
                    ),
                ),
                (
                    "reference_client",
                    models.CharField(
                        default="",
                        help_text="Référence donnée par le client à sa propre commande (numéro de bon de commande, etc.).",
                        max_length=100,
                        verbose_name="réf. commande client",
                    ),
                ),
                ("date_commande", models.DateField(verbose_name="date de commande")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("soldee", "Soldée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresse_facturation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.adresse",
                        verbose_name="adresse de facturation",
                    ),
                ),
                (
                    "adresse_livraison",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.adresse",
                        verbose_name="adresse de livraison",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Pré-rempli depuis le devis s'il y en a un, modifiable ensuite.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.tiers",
                        verbose_name="client",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optionnel : une commande peut être créée directement, sans devis d'origine.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="chiffrage.devis",
                        verbose_name="devis",
                    ),
                ),
                (
                    "devise",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Par défaut celle du client si renseignée",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.devise",
                        verbose_name="devise",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Commande",
                "verbose_name_plural": "historical Commandes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDevis",
            fields=[
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="numéro"
                    ),
                ),
                ("date_creation", models.DateField(verbose_name="date de création")),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "taux_marge_globale",
                    models.FloatField(
                        blank=True,
                        help_text="Optionnel, écrase les marges par défaut",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="taux de marge globale",
                    ),
                ),
                (
                    "delai",
                    models.CharField(
                        blank=True,
                        help_text="Délai de livraison annoncé. Texte libre : des suggestions viennent du référentiel « Délais proposés » (commercial.DelaiPropose), mais toute valeur saisie est acceptée.",
                        max_length=100,
                        verbose_name="délai",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresse_facturation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.adresse",
                        verbose_name="adresse de facturation",
                    ),
                ),
                (
                    "adresse_livraison",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.adresse",
                        verbose_name="adresse de livraison",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.tiers",
                        verbose_name="client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Devis",
                "verbose_name_plural": "historical Devis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDevisLigne",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (glisser-déposer sur la fiche devis) — repris tel quel sur la commande.",
                        verbose_name="ordre",
                    ),
                ),
                (
                    "quantite",
                    models.FloatField(
                        validators=[chiffrage.models._strictement_positif],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "cout_matiere_calcule",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="coût matière calculé",
                    ),
                ),
                (
                    "taux_marge_matiere_applique",
                    models.FloatField(
                        blank=True,
                        help_text="Pré-rempli depuis l'article, éditable",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="taux de marge matière appliqué",
                    ),
                ),
                (
                    "prix_vente_unitaire_force",
                    models.FloatField(
                        blank=True,
                        help_text="Si renseigné, remplace le calcul automatique (coût matière × marge) : prix de vente matière de la ligne = quantité × ce prix unitaire.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Ne peut pas être négatif."
                            )
                        ],
                        verbose_name="prix de vente unitaire forcé (HT)",
                    ),
                ),
                (
                    "prix_vente_matiere",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="prix de vente matière (HT)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="technique.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="chiffrage.devis",
                        verbose_name="devis",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taux_tva",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=chiffrage.models._taux_tva_par_defaut,
                        help_text="Pré-rempli avec le taux par défaut du référentiel, modifiable par ligne",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commercial.tauxtva",
                        verbose_name="taux de TVA",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ligne de devis",
                "verbose_name_plural": "historical Lignes de devis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
