# Generated by Django 5.2.17 on 2026-10-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0016_historique_devis_commande"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commande",
            options={
                "ordering": ["-date_commande", "numero"],
                "permissions": [("annuler_commande", "Peut annuler une commande")],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="devis",
            options={
                "ordering": ["-date_creation", "numero"],
                "permissions": [
                    ("valider_devis", "Peut valider un devis"),
                    (
                        "valider_vente_sous_cout",
                        "Peut valider un devis vendu sous le coût",
                    ),
                ],
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
    ]
