# Generated by Django 5.2.17 on 2026-10-03 07:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0017_permissions_metier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livraison",
            options={
                "ordering": ["-date_livraison", "numero"],
                "permissions": [("annuler_livraison", "Peut annuler une livraison")],
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
            },
        ),
        migrations.AddField(
            model_name="livraison",
            name="date_annulation",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="annulée le"
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="motif_annulation",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                verbose_name="motif d'annulation",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="statut",
            field=models.CharField(
                choices=[("validee", "Validée"), ("annulee", "Annulée")],
                default="validee",
                editable=False,
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="utilisateur_annulation",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livraisons_annulees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="annulée par",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLivraison",
            fields=[
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="numéro"
                    ),
                ),
                (
                    "date_livraison",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date de livraison",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("validee", "Validée"), ("annulee", "Annulée")],
                        default="validee",
                        editable=False,
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_annulation",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="annulée le"
                    ),
                ),
                (
                    "motif_annulation",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="motif d'annulation",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="chiffrage.commande",
                        verbose_name="commande",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur_annulation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="annulée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Livraison",
                "verbose_name_plural": "historical Livraisons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
