# Generated by Django 5.2.17 on 2026-10-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0018_livraison_annulable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordrefabrication",
            options={
                "ordering": ["-date_lancement", "numero"],
                "permissions": [
                    (
                        "voir_marges",
                        "Peut consulter les marges réelles et taux de charge (pilotage)",
                    )
                ],
                "verbose_name": "Ordre de fabrication",
                "verbose_name_plural": "Ordres de fabrication",
            },
        ),
    ]
