# Generated by Django 5.2.17 on 2026-10-03 09:02

import django.db.models.deletion
from django.db import migrations, models


def devis_deja_commandes_acceptes(apps, schema_editor):
    """Un devis dont une commande est issue a, de fait, été accepté. Les autres gardent
    « en attente » et aucune date de validité n'est inventée pour les devis existants."""
    Devis = apps.get_model("chiffrage", "Devis")
    Commande = apps.get_model("chiffrage", "Commande")
    numeros = Commande.objects.exclude(devis__isnull=True).values_list("devis_id", flat=True)
    Devis.objects.filter(pk__in=list(numeros)).update(issue="accepte")


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0019_permission_voir_marges"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="date_validite",
            field=models.DateField(
                blank=True,
                help_text="Fin de validité de l'offre. Posée à la validation (30 jours par défaut) ; vide = sans limite.",
                null=True,
                verbose_name="valable jusqu'au",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="devis_origine",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="chiffrage.devis",
                verbose_name="révision de",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="issue",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente de réponse"),
                    ("accepte", "Accepté"),
                    ("refuse", "Refusé"),
                    ("remplace", "Remplacé par une révision"),
                ],
                default="en_attente",
                help_text="Passe à « Accepté » à la création de la commande, à « Remplacé » quand on révise le devis.",
                max_length=12,
                verbose_name="réponse du client",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="motif_refus",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motif du refus"
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="revision",
            field=models.PositiveSmallIntegerField(
                default=1, editable=False, verbose_name="révision"
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="date_validite",
            field=models.DateField(
                blank=True,
                help_text="Fin de validité de l'offre. Posée à la validation (30 jours par défaut) ; vide = sans limite.",
                null=True,
                verbose_name="valable jusqu'au",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="devis_origine",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chiffrage.devis",
                verbose_name="révision de",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="issue",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente de réponse"),
                    ("accepte", "Accepté"),
                    ("refuse", "Refusé"),
                    ("remplace", "Remplacé par une révision"),
                ],
                default="en_attente",
                help_text="Passe à « Accepté » à la création de la commande, à « Remplacé » quand on révise le devis.",
                max_length=12,
                verbose_name="réponse du client",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="motif_refus",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motif du refus"
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="revision",
            field=models.PositiveSmallIntegerField(
                default=1, editable=False, verbose_name="révision"
            ),
        ),
        migrations.RunPython(devis_deja_commandes_acceptes, migrations.RunPython.noop),
    ]
