# Generated by Django 5.2.17 on 2026-10-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0020_cycle_de_vie_devis"),
        ("stock", "0005_tracabilite_matiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="livraisonligne",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour livrer une coulée précise (certificat 3.1). Vide : lots consommés du plus ancien au plus récent.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livraisons_lignes",
                to="stock.lot",
                verbose_name="lot livré",
            ),
        ),
    ]
