# Generated by Django 5.2.17 on 2026-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0021_tracabilite_matiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordrefabrication",
            name="derniere_erreur",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="dernière erreur de synchronisation",
            ),
        ),
        migrations.AddField(
            model_name="ordrefabrication",
            name="empreinte_envoyee",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="empreinte du dernier envoi réussi",
            ),
        ),
        migrations.AddField(
            model_name="ordrefabrication",
            name="prochaine_tentative",
            field=models.DateTimeField(
                blank=True,
                help_text="Délai croissant entre deux tentatives ; vide = à reprendre dès la prochaine exécution.",
                null=True,
                verbose_name="prochaine reprise automatique",
            ),
        ),
    ]
