# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0022_synchro_planning_fiable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandeligne",
            name="prix_vente_unitaire",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=6,
                help_text="Pré-rempli depuis le devis à la création de la commande, modifiable ensuite.",
                max_digits=16,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix de vente unitaire (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="taux_marge_globale",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Optionnel, écrase les marges par défaut",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge globale",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="cout_matiere_calcule",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="coût matière calculé",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_matiere",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="prix de vente matière (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_unitaire_force",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                help_text="Si renseigné, remplace le calcul automatique (coût matière × marge) : prix de vente matière de la ligne = quantité × ce prix unitaire.",
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix de vente unitaire forcé (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="taux_marge_matiere_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis l'article, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge matière appliqué",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="cout_calcule",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="coût calculé",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="prix_vente",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="prix de vente (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="taux_marge_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis le poste, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge appliqué",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevis",
            name="taux_marge_globale",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Optionnel, écrase les marges par défaut",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge globale",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="cout_matiere_calcule",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="coût matière calculé",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="prix_vente_matiere",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="prix de vente matière (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="prix_vente_unitaire_force",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=4,
                help_text="Si renseigné, remplace le calcul automatique (coût matière × marge) : prix de vente matière de la ligne = quantité × ce prix unitaire.",
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="prix de vente unitaire forcé (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="taux_marge_matiere_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis l'article, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge matière appliqué",
            ),
        ),
    ]
