# Generated by Django 5.2.17 on 2026-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0023_passage_en_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="motif_revision",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Ce qui change par rapport à l'indice précédent (renseigné à la création de la révision).",
                max_length=200,
                verbose_name="motif de la révision",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevis",
            name="motif_revision",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Ce qui change par rapport à l'indice précédent (renseigné à la création de la révision).",
                max_length=200,
                verbose_name="motif de la révision",
            ),
        ),
    ]
