# Generated by Django 5.2.17 on 2026-10-03 13:03

import django.db.models.deletion
from django.db import migrations, models


def relier_ofs_existants(apps, schema_editor):
    """Les OF créés avant cette version couvrent les lignes de leur commande portant le même article."""
    OrdreFabrication = apps.get_model("chiffrage", "OrdreFabrication")
    CommandeLigne = apps.get_model("chiffrage", "CommandeLigne")
    for of in OrdreFabrication.objects.all():
        lignes = list(CommandeLigne.objects.filter(commande_id=of.commande_id, article_id=of.article_id))
        if lignes:
            of.lignes_commande.set(lignes)
            dates = [l.date_livraison_prevue for l in lignes if l.date_livraison_prevue]
            if dates:
                of.date_livraison_prevue = min(dates)
                of.save(update_fields=["date_livraison_prevue"])


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0024_indices_devis"),
        ("technique", "0006_passage_en_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordrefabrication",
            name="date_livraison_prevue",
            field=models.DateField(
                blank=True,
                help_text="Date de livraison la plus proche parmi les lignes de commande couvertes (reprise à la création).",
                null=True,
                verbose_name="livraison prévue",
            ),
        ),
        migrations.AddField(
            model_name="ordrefabrication",
            name="lignes_commande",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plusieurs lignes d'un même article peuvent être regroupées dans un seul ordre.",
                related_name="ordres_fabrication",
                to="chiffrage.commandeligne",
                verbose_name="lignes de commande couvertes",
            ),
        ),
        migrations.CreateModel(
            name="ComposantOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_par_unite",
                    models.FloatField(
                        help_text="Telle que définie dans la nomenclature",
                        verbose_name="quantité par pièce",
                    ),
                ),
                (
                    "quantite_necessaire",
                    models.FloatField(
                        help_text="Quantité par pièce × quantité à fabriquer",
                        verbose_name="quantité nécessaire",
                    ),
                ),
                (
                    "longueur_mm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="longueur (mm)"
                    ),
                ),
                (
                    "largeur_mm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="largeur (mm)"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilisations_of",
                        to="technique.article",
                        verbose_name="composant",
                    ),
                ),
                (
                    "ordre_fabrication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composants",
                        to="chiffrage.ordrefabrication",
                        verbose_name="ordre de fabrication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composant d'ordre de fabrication",
                "verbose_name_plural": "Composants d'ordre de fabrication",
                "ordering": ["ordre_fabrication", "id"],
            },
        ),
        migrations.RunPython(relier_ofs_existants, migrations.RunPython.noop),
    ]
