# Generated by Django 5.2.17 on 2026-10-08 05:27

import comptes.champs
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0025_of_depuis_commande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="taux_marge_globale",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Optionnel, écrase les marges par défaut",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge globale (%)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="taux_marge_matiere_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis l'article, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge matière appliqué (%)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligneoperation",
            name="taux_marge_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis le poste, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge appliqué (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevis",
            name="taux_marge_globale",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Optionnel, écrase les marges par défaut",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge globale (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="taux_marge_matiere_applique",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                help_text="Pré-rempli depuis l'article, éditable",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Ne peut pas être négatif."
                    )
                ],
                verbose_name="taux de marge matière appliqué (%)",
            ),
        ),
    ]
