# Generated by Django 5.2.17 on 2026-10-09 11:52

import comptes.champs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0026_alter_devis_taux_marge_globale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devisligne",
            name="note_reglage",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=250,
                verbose_name="détail du réglage machine",
            ),
        ),
        migrations.AddField(
            model_name="devisligne",
            name="prix_vente_reglage",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part de la mise en place des tôles (réglage machine) comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglage machine (HT)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevisligne",
            name="note_reglage",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=250,
                verbose_name="détail du réglage machine",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevisligne",
            name="prix_vente_reglage",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part de la mise en place des tôles (réglage machine) comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglage machine (HT)",
            ),
        ),
    ]
