# Generated by Django 5.2.17 on 2026-10-10 18:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0027_reglage_par_tole"),
    ]

    operations = [
        migrations.AddField(
            model_name="devisligne",
            name="prix_vente_reglage_operations",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part des temps de réglage par lot des opérations de la gamme (colonne « Réglage (min) ») comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglages d'opérations (HT)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevisligne",
            name="prix_vente_reglage_operations",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part des temps de réglage par lot des opérations de la gamme (colonne « Réglage (min) ») comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglages d'opérations (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="devisligne",
            name="prix_vente_reglage",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part de la mise en place des tôles sur la machine de découpe (une fois par tôle, d'après l'imbrication) comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglage de tôle (HT)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevisligne",
            name="prix_vente_reglage",
            field=comptes.champs.ChampDecimal(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Part de la mise en place des tôles sur la machine de découpe (une fois par tôle, d'après l'imbrication) comprise dans le prix des opérations : information, déjà incluse.",
                max_digits=14,
                null=True,
                verbose_name="dont réglage de tôle (HT)",
            ),
        ),
    ]
