# Generated by Django 5.2.17 on 2026-09-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImbricationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("largeur_feuille_mm", models.FloatField()),
                ("longueur_feuille_mm", models.FloatField()),
                (
                    "marge_bord_mm",
                    models.FloatField(
                        default=5, help_text="Marge non utilisable en bord de feuille"
                    ),
                ),
                (
                    "espacement_pieces_mm",
                    models.FloatField(
                        default=5, help_text="Espacement minimal entre deux pièces"
                    ),
                ),
                ("nb_feuilles", models.PositiveIntegerField(blank=True, null=True)),
                ("surface_pieces_mm2", models.FloatField(blank=True, null=True)),
                ("surface_feuilles_mm2", models.FloatField(blank=True, null=True)),
                ("taux_utilisation_pct", models.FloatField(blank=True, null=True)),
                ("cout_matiere_estime", models.FloatField(blank=True, null=True)),
                ("pieces_non_placees", models.JSONField(blank=True, default=list)),
                ("date_calcul", models.DateTimeField(blank=True, null=True)),
                (
                    "article_matiere",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tôle (article matière première) utilisée, pour le chiffrage matière",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imbrications",
                        to="technique.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imbrication",
                "verbose_name_plural": "Imbrications",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PieceDecoupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "fichier_source",
                    models.FileField(upload_to="decoupe/sources/%Y/%m/"),
                ),
                (
                    "format_source",
                    models.CharField(
                        blank=True,
                        choices=[("dxf", "DXF"), ("dwg", "DWG")],
                        max_length=10,
                    ),
                ),
                (
                    "rotation_autorisee",
                    models.BooleanField(
                        default=True,
                        help_text="À décocher si le sens de la matière (fil, grain) impose l'orientation de la pièce",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente d'import"),
                            ("ok", "Importée"),
                            ("erreur", "Erreur d'import"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("message_erreur", models.TextField(blank=True)),
                ("avertissements", models.JSONField(blank=True, default=list)),
                ("surface_mm2", models.FloatField(blank=True, null=True)),
                (
                    "perimetre_decoupe_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Longueur totale à découper : contour extérieur + trous",
                        null=True,
                    ),
                ),
                (
                    "largeur_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Largeur du rectangle englobant",
                        null=True,
                    ),
                ),
                (
                    "hauteur_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Hauteur du rectangle englobant",
                        null=True,
                    ),
                ),
                (
                    "nb_contours_interieurs",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre de trous détectés"
                    ),
                ),
                (
                    "contour_json",
                    models.JSONField(
                        blank=True,
                        help_text="Contour extérieur et trous, coordonnées locales en mm",
                        null=True,
                    ),
                ),
                ("date_import", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article fabriqué correspondant, si déjà référencé au socle technique",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces_decoupe",
                        to="technique.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce à découper",
                "verbose_name_plural": "Pièces à découper",
                "ordering": ["-date_import"],
            },
        ),
        migrations.CreateModel(
            name="ImbricationPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_feuille", models.PositiveIntegerField()),
                ("x_mm", models.FloatField()),
                ("y_mm", models.FloatField()),
                (
                    "rotation_deg",
                    models.PositiveIntegerField(
                        choices=[(0, "0°"), (90, "90°")], default=0
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="decoupe.imbricationjob",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="decoupe.piecedecoupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Placements",
                "ordering": ["job", "numero_feuille", "y_mm", "x_mm"],
            },
        ),
        migrations.CreateModel(
            name="ImbricationLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="decoupe.imbricationjob",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_imbrication",
                        to="decoupe.piecedecoupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'imbrication",
                "verbose_name_plural": "Lignes d'imbrication",
                "unique_together": {("job", "piece")},
            },
        ),
    ]
