# Generated by Django 5.2.17 on 2026-09-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0001_initial"),
        ("technique", "0005_article_taux_tva"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilImportDecoupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Profil d'import",
                "verbose_name_plural": "Profils d'import",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="imbricationplacement",
            name="miroir",
            field=models.BooleanField(
                default=False,
                help_text="Pièce retournée (symétrie miroir) pour ce placement",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="a_gravure",
            field=models.BooleanField(
                default=False,
                help_text="Détecté automatiquement : le fichier contient des tracés classés « gravure »",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="calques_detectes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Calques trouvés dans le fichier source",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="epaisseur",
            field=models.FloatField(
                blank=True, help_text="Épaisseur de tôle (mm)", null=True
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="gravure_json",
            field=models.JSONField(
                blank=True,
                help_text="Tracés de gravure/marquage, repère local en mm",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="longueur_gravure_mm",
            field=models.FloatField(
                blank=True,
                help_text="Longueur totale des tracés de gravure/marquage",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces_decoupe",
                to="technique.matiere",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="pas_rotation_deg",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(5, "5°"), (45, "45°"), (90, "90°")],
                help_text="Pas de rotation autorisé pour l'imbrication — vide si aucune rotation n'est permise (sens de la matière imposé)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="pliage_json",
            field=models.JSONField(
                blank=True,
                help_text="Lignes de pliage détectées, repère local en mm",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="symetrie_autorisee",
            field=models.BooleanField(
                default=True,
                help_text="À décocher si la pièce ne peut pas être retournée (miroir) — gravure, marquage non symétrique...",
            ),
        ),
        migrations.AlterField(
            model_name="imbricationplacement",
            name="rotation_deg",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Angle de rotation appliqué (pas de 5°)"
            ),
        ),
        migrations.AlterField(
            model_name="piecedecoupe",
            name="rotation_autorisee",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="profil_import",
            field=models.ForeignKey(
                blank=True,
                help_text="Règles de classement des calques (découpe / gravure / pliage / ignoré) utilisées à l'import",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces_decoupe",
                to="decoupe.profilimportdecoupe",
            ),
        ),
        migrations.CreateModel(
            name="RegleProfilImportDecoupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calque",
                    models.CharField(
                        help_text="Nom du calque DXF/DWG (comparaison insensible à la casse)",
                        max_length=100,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("decoupe", "Découpe"),
                            ("gravure", "Gravure / marquage"),
                            ("pliage", "Pliage"),
                            ("ignore", "Ignoré"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles",
                        to="decoupe.profilimportdecoupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de profil d'import",
                "verbose_name_plural": "Règles de profil d'import",
                "ordering": ["calque"],
                "unique_together": {("profil", "calque")},
            },
        ),
    ]
