# Generated by Django 5.2.17 on 2026-09-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0003_backfill_pas_rotation_deg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="piecedecoupe",
            name="rotation_autorisee",
        ),
    ]
