# Generated by Django 5.2.17 on 2026-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0004_remove_piecedecoupe_rotation_autorisee"),
    ]

    operations = [
        migrations.AddField(
            model_name="imbricationjob",
            name="coin_depart",
            field=models.CharField(
                choices=[
                    ("bas_gauche", "Bas gauche"),
                    ("bas_droite", "Bas droite"),
                    ("haut_gauche", "Haut gauche"),
                    ("haut_droite", "Haut droite"),
                ],
                default="bas_gauche",
                help_text="Coin de la feuille où démarre le placement (convention machine la plus courante : bas gauche)",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="imbricationjob",
            name="direction",
            field=models.CharField(
                choices=[
                    ("horizontal", "Horizontal (rangées empilées verticalement)"),
                    ("vertical", "Vertical (colonnes empilées horizontalement)"),
                ],
                default="horizontal",
                help_text="Sens de remplissage des pièces sur la feuille",
                max_length=10,
            ),
        ),
    ]
