# Generated by Django 5.2.17 on 2026-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0005_imbricationjob_coin_depart_imbricationjob_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="regles_calques_manuelles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Classement calque → rôle choisi à la main pour cette pièce (prioritaire sur le profil d'import)",
            ),
        ),
    ]
