# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0006_piecedecoupe_regles_calques_manuelles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imbricationjob",
            name="cout_matiere_estime",
            field=comptes.champs.ChampDecimal(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
