# Generated by Django 5.2.17 on 2026-10-05 11:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0007_passage_en_decimal"),
        ("technique", "0007_gamme_origine"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="qualite_coupe",
            field=models.DecimalField(
                choices=[
                    (Decimal("1.5"), "1,5 — Extra brut"),
                    (Decimal("2.0"), "2 — Brut"),
                    (Decimal("3.0"), "3 — Moyen+"),
                    (Decimal("4.0"), "4 — Fin"),
                    (Decimal("5.0"), "5 — Extra fin"),
                ],
                decimal_places=1,
                default=Decimal("3.0"),
                help_text="Niveau de qualité du jet d'eau (1,5 extra brut → 5 extra fin) : plus c'est fin, plus la coupe est lente.",
                max_digits=2,
                verbose_name="qualité de coupe",
            ),
        ),
        migrations.CreateModel(
            name="ParametreCoupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procede",
                    models.CharField(
                        choices=[("jet_eau", "Jet d'eau (eau + abrasif)")],
                        default="jet_eau",
                        max_length=10,
                        verbose_name="procédé",
                    ),
                ),
                ("epaisseur_mm", models.FloatField(verbose_name="épaisseur (mm)")),
                (
                    "usinabilite",
                    models.FloatField(
                        blank=True,
                        help_text="Indice d'usinabilité du logiciel de la machine (information)",
                        null=True,
                        verbose_name="usinabilité",
                    ),
                ),
                (
                    "mode_percage",
                    models.CharField(
                        choices=[
                            ("stationnaire_hp", "Stationnaire haute pression"),
                            ("stationnaire_bp", "Stationnaire basse pression"),
                            ("circulaire_hp", "Circulaire haute pression"),
                            ("circulaire_bp", "Circulaire basse pression"),
                        ],
                        default="stationnaire_hp",
                        max_length=16,
                        verbose_name="mode de perçage",
                    ),
                ),
                (
                    "percage_stationnaire_hp_s",
                    models.FloatField(
                        default=0, verbose_name="perçage stationnaire HP (s)"
                    ),
                ),
                (
                    "percage_stationnaire_bp_s",
                    models.FloatField(
                        default=0, verbose_name="perçage stationnaire BP (s)"
                    ),
                ),
                (
                    "percage_circulaire_hp_tours",
                    models.FloatField(
                        default=0, verbose_name="perçage circulaire HP (tours)"
                    ),
                ),
                (
                    "percage_circulaire_bp_tours",
                    models.FloatField(
                        default=0, verbose_name="perçage circulaire BP (tours)"
                    ),
                ),
                (
                    "diametre_percage_mm",
                    models.FloatField(
                        default=1.4, verbose_name="diamètre de perçage (mm)"
                    ),
                ),
                (
                    "temporisation_pointage_s",
                    models.FloatField(
                        default=0, verbose_name="temporisation de pointage (s)"
                    ),
                ),
                (
                    "temporisation_marquage_s",
                    models.FloatField(
                        default=0, verbose_name="temporisation de marquage (s)"
                    ),
                ),
                (
                    "vitesse_marquage_mm_min",
                    models.FloatField(
                        default=4000, verbose_name="vitesse de marquage (mm/min)"
                    ),
                ),
                (
                    "percement_lineaire_mm",
                    models.FloatField(
                        default=0,
                        help_text="Amorce de coupe avant le contour",
                        verbose_name="percement linéaire (mm)",
                    ),
                ),
                (
                    "chevauchement_mm",
                    models.FloatField(
                        default=0,
                        help_text="Recouvrement à la fermeture d'un contour",
                        verbose_name="chevauchement (mm)",
                    ),
                ),
                (
                    "intervalle_pieces_mm",
                    models.FloatField(
                        default=4,
                        help_text="Espacement utilisé pour l'imbrication",
                        verbose_name="intervalle entre pièces (mm)",
                    ),
                ),
                (
                    "rayon_pleine_vitesse_mm",
                    models.FloatField(
                        default=25,
                        help_text="Un arc de rayon supérieur est coupé à la vitesse élevée ; en dessous la vitesse décroît jusqu'à la vitesse basse.",
                        verbose_name="rayon de pleine vitesse (mm)",
                    ),
                ),
                (
                    "seuil_angle_coin_deg",
                    models.FloatField(
                        default=30,
                        help_text="Au-delà de ce changement de direction, c'est un coin (ralentissement)",
                        verbose_name="angle d'un coin (°)",
                    ),
                ),
                (
                    "coefficient_ajustement",
                    models.FloatField(
                        default=1,
                        help_text="Multiplie le temps calculé : à caler sur les temps réellement donnés par le logiciel de la machine.",
                        verbose_name="coefficient d'ajustement",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametres_coupe",
                        to="technique.matiere",
                        verbose_name="matière",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine de coupe : son tarif horaire valorise le temps calculé dans la gamme.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametres_coupe",
                        to="technique.postetravail",
                        verbose_name="poste de travail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de coupe",
                "verbose_name_plural": "Paramètres de coupe",
                "ordering": ["procede", "matiere", "epaisseur_mm"],
            },
        ),
        migrations.CreateModel(
            name="VitesseCoupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualite",
                    models.DecimalField(
                        choices=[
                            (Decimal("1.5"), "1,5 — Extra brut"),
                            (Decimal("2.0"), "2 — Brut"),
                            (Decimal("3.0"), "3 — Moyen+"),
                            (Decimal("4.0"), "4 — Fin"),
                            (Decimal("5.0"), "5 — Extra fin"),
                        ],
                        decimal_places=1,
                        max_digits=2,
                        verbose_name="qualité",
                    ),
                ),
                (
                    "vitesse_haute_mm_min",
                    models.FloatField(verbose_name="vitesse élevée (mm/min)"),
                ),
                (
                    "vitesse_basse_mm_min",
                    models.FloatField(verbose_name="vitesse basse (mm/min)"),
                ),
                (
                    "paliers",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Nombre de paliers de vitesse entre la basse et l'élevée dans les courbes",
                        verbose_name="paliers (N)",
                    ),
                ),
                (
                    "distance_acceleration_mm",
                    models.FloatField(
                        default=0, verbose_name="distance d'accélération A (mm)"
                    ),
                ),
                (
                    "distance_deceleration_mm",
                    models.FloatField(
                        default=0, verbose_name="distance de décélération R (mm)"
                    ),
                ),
                (
                    "coefficient_haut",
                    models.FloatField(default=1, verbose_name="coefficient haut"),
                ),
                (
                    "coefficient_bas",
                    models.FloatField(default=1, verbose_name="coefficient bas"),
                ),
                (
                    "facteur_arc",
                    models.FloatField(default=1, verbose_name="facteur par arc"),
                ),
                (
                    "parametre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitesses",
                        to="decoupe.parametrecoupe",
                        verbose_name="paramètre de coupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vitesse de coupe",
                "verbose_name_plural": "Vitesses de coupe",
                "ordering": ["parametre", "qualite"],
            },
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.UniqueConstraint(
                fields=("procede", "matiere", "epaisseur_mm"),
                name="unique_parametre_coupe",
            ),
        ),
        migrations.AddConstraint(
            model_name="vitessecoupe",
            constraint=models.UniqueConstraint(
                fields=("parametre", "qualite"), name="unique_vitesse_coupe"
            ),
        ),
    ]
