# Generated by Django 5.2.17 on 2026-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0008_piecedecoupe_qualite_coupe_parametrecoupe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrecoupe",
            name="origine",
            field=models.CharField(
                choices=[
                    ("machine", "Relevées sur la machine"),
                    ("calcule", "Calculées depuis l'usinabilité (estimation)"),
                ],
                default="machine",
                help_text="Les vitesses « calculées » sont une estimation à confirmer ; celles relevées sur la machine ne sont jamais écrasées par un calcul.",
                max_length=8,
                verbose_name="origine des vitesses",
            ),
        ),
        migrations.AlterField(
            model_name="parametrecoupe",
            name="usinabilite",
            field=models.FloatField(
                blank=True,
                help_text="Indice d'usinabilité du logiciel de la machine ; vide : celui de la matière. Sert à calculer les vitesses.",
                null=True,
                verbose_name="usinabilité",
            ),
        ),
    ]
