# Generated by Django 5.2.17 on 2026-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0009_parametrecoupe_origine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrecoupe",
            name="rayon_pleine_vitesse_mm",
            field=models.FloatField(
                default=18.3,
                help_text="Un arc de rayon supérieur est coupé à la vitesse élevée ; en dessous la vitesse décroît jusqu'à la vitesse basse.",
                verbose_name="rayon de pleine vitesse (mm)",
            ),
        ),
    ]
