# Generated by Django 5.2.17 on 2026-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0010_alter_parametrecoupe_rayon_pleine_vitesse_mm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametrecoupe",
            name="rayon_pleine_vitesse_mm",
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="deplacement_par_contour_s",
            field=models.FloatField(
                default=2.75,
                help_text="Transferts hauts (déplacements à vide) comptés par contour",
                verbose_name="déplacement entre contours (s)",
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="facteur_percage",
            field=models.FloatField(
                default=0.5,
                help_text="Multiplie le temps de perçage calculé (tous les contours ne sont pas percés de la même façon) : calé sur la durée de perçage donnée par le logiciel de la machine.",
                verbose_name="facteur de perçage",
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="rayon_pleine_vitesse_coef",
            field=models.FloatField(
                default=1.98,
                help_text="Un arc dont le rayon dépasse ce multiple de l'épaisseur est coupé à la vitesse élevée ; en dessous la vitesse décroît jusqu'à la vitesse basse (le jet se déporte d'autant plus dans les courbes que la tôle est épaisse).",
                verbose_name="rayon de pleine vitesse (× épaisseur)",
            ),
        ),
    ]
