# Generated by Django 5.2.17 on 2026-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0011_remove_parametrecoupe_rayon_pleine_vitesse_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrecoupe",
            name="facteur_vitesse_courbe",
            field=models.FloatField(
                default=1.243,
                help_text="Multiplie la vitesse basse dans les courbes et les coins (le logiciel de la machine ne descend pas aussi bas que la vitesse basse affichée) : calé sur les temps réels.",
                verbose_name="facteur de vitesse en courbe",
            ),
        ),
        migrations.AlterField(
            model_name="parametrecoupe",
            name="rayon_pleine_vitesse_coef",
            field=models.FloatField(
                default=2.227,
                help_text="Un arc dont le rayon dépasse ce multiple de l'épaisseur est coupé à la vitesse élevée ; en dessous la vitesse décroît jusqu'à la vitesse basse (le jet se déporte d'autant plus dans les courbes que la tôle est épaisse).",
                verbose_name="rayon de pleine vitesse (× épaisseur)",
            ),
        ),
    ]
