# Generated by Django 5.2.17 on 2026-10-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0013_recaler_parametres_calcules"),
        ("technique", "0008_matiere_usinabilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="imbrication_chiffrage",
            field=models.BooleanField(
                default=False,
                help_text="La matière d'un article fabriqué lié à cette pièce est calculée par imbrication (surface consommée avec les chutes, selon la quantité) au lieu du rectangle de la nomenclature.",
                verbose_name="chiffrer la matière par imbrication",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="marge_bord_mm",
            field=models.FloatField(
                default=5,
                help_text="Bande non utilisable sur le pourtour de la tôle",
                verbose_name="marge de bord (mm)",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="taux_chute_recuperable",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Part des chutes réutilisée ailleurs : elle n'est pas facturée à la pièce (0 = toutes les chutes sont facturées).",
                max_digits=5,
                verbose_name="chute récupérable (%)",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="tole",
            field=models.ForeignKey(
                blank=True,
                help_text="Article matière première (tôle) dans lequel la pièce est découpée : son prix sert au coût matière.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces_decoupees_dans",
                to="technique.article",
                verbose_name="tôle",
            ),
        ),
        migrations.CreateModel(
            name="FormatTole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text="Ex. « 3000 × 1500 » (laissé vide : déduit des dimensions)",
                        max_length=60,
                        verbose_name="libellé",
                    ),
                ),
                ("largeur_mm", models.FloatField(verbose_name="largeur (mm)")),
                ("longueur_mm", models.FloatField(verbose_name="longueur (mm)")),
                (
                    "actif",
                    models.BooleanField(
                        default=True, verbose_name="proposé dans les simulations"
                    ),
                ),
            ],
            options={
                "verbose_name": "Format de tôle",
                "verbose_name_plural": "Formats de tôle",
                "ordering": ["-longueur_mm", "-largeur_mm"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("largeur_mm", "longueur_mm"), name="unique_format_tole"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="format_tole",
            field=models.ForeignKey(
                blank=True,
                help_text="Format retenu après simulation d'imbrication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="decoupe.formattole",
                verbose_name="format de tôle retenu",
            ),
        ),
    ]
