# Generated by Django 5.2.17 on 2026-10-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0015_formats_tole_standard"),
        ("technique", "0010_familles_matiere_standard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametrecoupe",
            options={
                "ordering": ["procede", "famille", "matiere", "epaisseur_mm"],
                "verbose_name": "Paramètre de coupe",
                "verbose_name_plural": "Paramètres de coupe",
            },
        ),
        migrations.RemoveConstraint(
            model_name="parametrecoupe",
            name="unique_parametre_coupe",
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="famille",
            field=models.ForeignKey(
                blank=True,
                help_text="Cas général : le paramètre vaut pour toutes les nuances de la famille (S235, S355… pour « Acier »).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametres_coupe",
                to="technique.famillematiere",
                verbose_name="famille de matière",
            ),
        ),
        migrations.AlterField(
            model_name="parametrecoupe",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                help_text="Exception : un paramètre propre à une seule nuance, qui prend le pas sur celui de sa famille. Laisser vide en général.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametres_coupe",
                to="technique.matiere",
                verbose_name="nuance précise",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("famille__isnull", False), ("matiere__isnull", True)),
                    models.Q(("famille__isnull", True), ("matiere__isnull", False)),
                    _connector="OR",
                ),
                name="parametre_coupe_famille_xor_matiere",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("famille__isnull", False)),
                fields=("procede", "famille", "epaisseur_mm"),
                name="unique_parametre_coupe_famille",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matiere__isnull", False)),
                fields=("procede", "matiere", "epaisseur_mm"),
                name="unique_parametre_coupe_matiere",
            ),
        ),
    ]
