# Generated by Django 5.2.17 on 2026-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0017_base_coupe_par_famille"),
        ("technique", "0011_gaz_laser_famille"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglageProcede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procede",
                    models.CharField(
                        choices=[
                            ("jet_eau", "Jet d'eau (eau + abrasif)"),
                            ("laser", "Laser fibre"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="procédé",
                    ),
                ),
                (
                    "coefficient_vitesse",
                    models.FloatField(
                        default=1,
                        help_text="Laser : multiplie les vitesses de coupe du constructeur (0,85 = 15 % plus lent) pour tenir compte des vitesses surestimées constatées. Sans effet sur le jet d'eau, dont le calcul est déjà calé sur des temps réels.",
                        verbose_name="coefficient de pondération des vitesses",
                    ),
                ),
                (
                    "espacement_minimum_mm",
                    models.FloatField(
                        default=4,
                        help_text="Plancher de l'écart entre deux pièces à l'imbrication, quelles que soient la matière et l'épaisseur (jet d'eau : 6 ; laser : 10). Au laser, la base donne un écart plus grand quand l'épaisseur augmente : le plus grand des deux est retenu.",
                        verbose_name="écart minimal entre pièces (mm)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglage de coupe",
                "verbose_name_plural": "Réglages de coupe",
                "ordering": ["procede"],
            },
        ),
        migrations.AlterModelOptions(
            name="parametrecoupe",
            options={
                "ordering": ["procede", "famille", "matiere", "gaz", "epaisseur_mm"],
                "verbose_name": "Paramètre de coupe",
                "verbose_name_plural": "Paramètres de coupe",
            },
        ),
        migrations.RemoveConstraint(
            model_name="parametrecoupe",
            name="unique_parametre_coupe_famille",
        ),
        migrations.RemoveConstraint(
            model_name="parametrecoupe",
            name="unique_parametre_coupe_matiere",
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="consommation_gaz_m3_h",
            field=models.FloatField(
                blank=True, null=True, verbose_name="consommation de gaz (m³/h)"
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="gaz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O2", "Oxygène (O₂)"),
                    ("N2", "Azote (N₂)"),
                    ("Air", "Air comprimé"),
                ],
                help_text="Laser : un paramètre par gaz.",
                max_length=4,
                verbose_name="gaz de coupe",
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="puissance_kw",
            field=models.FloatField(
                blank=True, null=True, verbose_name="puissance absorbée (kW)"
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="remarque",
            field=models.CharField(blank=True, max_length=250, verbose_name="remarque"),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="vitesse_coupe_max_m_min",
            field=models.FloatField(
                blank=True,
                help_text="Laser : vitesse maximale du constructeur (qualité et tolérance de focale réduites).",
                null=True,
                verbose_name="vitesse maximale (m/min)",
            ),
        ),
        migrations.AddField(
            model_name="parametrecoupe",
            name="vitesse_coupe_production_m_min",
            field=models.FloatField(
                blank=True,
                help_text="Laser : vitesse retenue pour le calcul du temps (avant le coefficient de pondération des réglages de coupe).",
                null=True,
                verbose_name="vitesse de production (m/min)",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="gaz_coupe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O2", "Oxygène (O₂)"),
                    ("N2", "Azote (N₂)"),
                    ("Air", "Air comprimé"),
                ],
                help_text="Laser uniquement. Vide : le gaz usuel de la famille de matière (oxygène pour l'acier, azote pour l'inox et l'alu…).",
                max_length=4,
                verbose_name="gaz de coupe (laser)",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="procede",
            field=models.CharField(
                choices=[
                    ("jet_eau", "Jet d'eau (eau + abrasif)"),
                    ("laser", "Laser fibre"),
                ],
                default="jet_eau",
                help_text="Machine utilisée pour estimer le temps de découpe, l'écart entre pièces et la gamme. Au laser, une épaisseur absente de la base n'est pas réalisable.",
                max_length=10,
                verbose_name="procédé de coupe",
            ),
        ),
        migrations.AlterField(
            model_name="parametrecoupe",
            name="procede",
            field=models.CharField(
                choices=[
                    ("jet_eau", "Jet d'eau (eau + abrasif)"),
                    ("laser", "Laser fibre"),
                ],
                default="jet_eau",
                max_length=10,
                verbose_name="procédé",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("famille__isnull", False)),
                fields=("procede", "famille", "gaz", "epaisseur_mm"),
                name="unique_parametre_coupe_famille",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametrecoupe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matiere__isnull", False)),
                fields=("procede", "matiere", "gaz", "epaisseur_mm"),
                name="unique_parametre_coupe_matiere",
            ),
        ),
    ]
