# Generated by Django 5.2.17 on 2026-10-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0025_of_depuis_commande"),
        ("decoupe", "0019_base_coupe_laser"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="article_cree_automatiquement",
            field=models.BooleanField(
                default=False,
                help_text="L'article fabriqué a été créé par l'import du devis : il disparaît avec la pièce s'il n'est utilisé nulle part.",
                verbose_name="article créé à l'import",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="devis",
            field=models.ForeignKey(
                blank=True,
                help_text="Devis dans lequel la pièce a été importée (panneau « Pièces à découper » du devis).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces_decoupe",
                to="chiffrage.devis",
                verbose_name="devis d'origine",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="quantite",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantité à découper pour le devis d'origine.",
                verbose_name="quantité",
            ),
        ),
    ]
