# Generated by Django 5.2.17 on 2026-10-07 16:33

from django.db import migrations, models


def capacites(apps, schema_editor):
    Reglage = apps.get_model("decoupe", "ReglageProcede")
    Reglage.objects.filter(procede="jet_eau").update(capacite_largeur_mm=2000, capacite_longueur_mm=4000)
    Reglage.objects.filter(procede="laser").update(capacite_largeur_mm=1500, capacite_longueur_mm=3000)



class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0020_piecedecoupe_article_cree_automatiquement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglageprocede",
            name="capacite_largeur_mm",
            field=models.FloatField(
                default=0,
                help_text="Plus petite dimension de la plus grande tôle que la machine peut recevoir. 0 : pas de limite.",
                verbose_name="capacité de la machine : largeur (mm)",
            ),
        ),
        migrations.AddField(
            model_name="reglageprocede",
            name="capacite_longueur_mm",
            field=models.FloatField(
                default=0,
                help_text="Plus grande dimension de la plus grande tôle que la machine peut recevoir (jet d'eau : 4000 × 2000 ; laser : 3000 × 1500). 0 : pas de limite.",
                verbose_name="capacité de la machine : longueur (mm)",
            ),
        ),
        migrations.RunPython(capacites, migrations.RunPython.noop),
    ]
