# Generated by Django 5.2.17 on 2026-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0021_capacite_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="imbrication_forme",
            field=models.BooleanField(
                default=True,
                help_text="L'imbrication tient compte du contour réel des pièces (trous compris) et non de leur seul rectangle englobant : moins de chutes, calcul un peu plus long.",
                verbose_name="imbriquer selon la forme",
            ),
        ),
    ]
