# Generated by Django 5.2.17 on 2026-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0022_imbrication_forme"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="parametres_forme",
            field=models.JSONField(
                blank=True,
                help_text="Recette de la pièce créée depuis la bibliothèque de formes ({famille, cotes}) ; vide pour une pièce importée d'un fichier.",
                null=True,
                verbose_name="forme paramétrique",
            ),
        ),
        migrations.CreateModel(
            name="NormeCote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "famille",
                    models.CharField(
                        choices=[
                            ("bride_en1092", "Bride EN 1092-1"),
                            ("rondelle", "Rondelle ISO"),
                        ],
                        max_length=20,
                        verbose_name="famille",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="« DN50 PN16 », « ISO 7089 M10 »…",
                        max_length=60,
                        verbose_name="désignation",
                    ),
                ),
                (
                    "valeurs",
                    models.JSONField(
                        default=dict,
                        help_text="Bride : dn, pn, D (Ø extérieur), K (cercle de perçage), n (nombre de trous), L (Ø des trous), tube_od (Ø du tube). Rondelle : norme, taille, d1 (Ø intérieur), d2 (Ø extérieur), h (épaisseur).",
                        verbose_name="cotes (mm)",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="source"),
                ),
                (
                    "verifie",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez une fois les cotes contrôlées avec la norme en vigueur : l'avertissement disparaît de l'écran du devis.",
                        verbose_name="vérifié",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "Cote normalisée",
                "verbose_name_plural": "Cotes normalisées",
                "ordering": ["famille", "ordre", "designation"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("famille", "designation"), name="unique_norme_cote"
                    )
                ],
            },
        ),
    ]
