# Generated by Django 5.2.17 on 2026-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0024_cotes_normalisees_initiales"),
    ]

    operations = [
        migrations.AddField(
            model_name="piecedecoupe",
            name="coin_depart",
            field=models.CharField(
                choices=[
                    ("bas_gauche", "En bas à gauche"),
                    ("haut_gauche", "En haut à gauche"),
                    ("bas_droite", "En bas à droite"),
                    ("haut_droite", "En haut à droite"),
                ],
                default="bas_gauche",
                help_text="Coin de la tôle où commence l'imbrication (origine de la machine). Les coins « en haut à gauche » et « en bas à droite » retournent les pièces : refusés si une pièce ne peut pas être retournée.",
                max_length=12,
                verbose_name="coin de départ",
            ),
        ),
        migrations.AddField(
            model_name="piecedecoupe",
            name="sens_imbrication",
            field=models.CharField(
                choices=[
                    ("longueur", "Dans le sens de la longueur de la tôle"),
                    ("largeur", "Dans le sens de la largeur de la tôle"),
                ],
                default="longueur",
                help_text="Sens dans lequel la tôle se remplit : la chute de bout est la bande qui reste, sur toute la largeur (ou toute la longueur) de la tôle, après la dernière pièce.",
                max_length=10,
                verbose_name="sens de l'imbrication",
            ),
        ),
    ]
