# Generated by Django 5.2.17 on 2026-10-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiffrage", "0026_alter_devis_taux_marge_globale_and_more"),
        ("decoupe", "0025_sens_et_coin_imbrication"),
        ("technique", "0013_alter_article_taux_marge_defaut_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "famille",
                    models.CharField(
                        choices=[
                            ("corniere", "Cornière"),
                            ("upn", "UPN"),
                            ("tube_carre", "Tube carré"),
                            ("tube_rectangulaire", "Tube rectangulaire"),
                            ("tube_rond", "Tube rond"),
                        ],
                        max_length=20,
                        verbose_name="famille",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="« L 50×50×5 », « UPN 100 », « Tube 40×40×3 »…",
                        max_length=60,
                        unique=True,
                        verbose_name="désignation",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=dict,
                        help_text="Cornière : a, b, e. UPN : h, b, tw, tf. Tube carré : c, e. Tube rectangulaire : h, b, e. Tube rond : d, e.",
                        verbose_name="cotes (mm)",
                    ),
                ),
                (
                    "masse_lineique",
                    models.FloatField(verbose_name="masse linéique (kg/m)"),
                ),
                (
                    "longueur_barre_mm",
                    models.FloatField(
                        default=6000,
                        help_text="Longueur de barre achetée, dont sont tirés les débits.",
                        verbose_name="longueur de barre (mm)",
                    ),
                ),
                (
                    "verifie",
                    models.BooleanField(
                        default=False,
                        help_text="Masses et cotes contrôlées avec le catalogue du fournisseur ou la norme.",
                        verbose_name="vérifié",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="source"),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matière première dont le coût sert au prix des débits : coût au mètre, au kilo (avec la masse linéique) ou à la barre.",
                        limit_choices_to={"nature": "matiere_premiere"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections_profile",
                        to="technique.article",
                        verbose_name="article d'achat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section de profilé",
                "verbose_name_plural": "Sections de profilés",
                "ordering": ["famille", "ordre", "designation"],
            },
        ),
        migrations.CreateModel(
            name="PieceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "longueur_mm",
                    models.FloatField(verbose_name="longueur hors tout (mm)"),
                ),
                (
                    "coupe_a_deg",
                    models.FloatField(
                        default=90,
                        help_text="90 : coupe droite ; 45 : biseau à 45°.",
                        verbose_name="coupe de l'extrémité A (°)",
                    ),
                ),
                (
                    "coupe_b_deg",
                    models.FloatField(
                        default=90, verbose_name="coupe de l'extrémité B (°)"
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="quantité"),
                ),
                ("article_cree_automatiquement", models.BooleanField(default=False)),
                (
                    "trait_scie_mm",
                    models.FloatField(default=3, verbose_name="trait de scie (mm)"),
                ),
                (
                    "marge_bout_mm",
                    models.FloatField(
                        default=0,
                        help_text="Longueur de barre perdue à l'extrémité avant la première coupe.",
                        verbose_name="chute de tête (mm)",
                    ),
                ),
                (
                    "taux_chute_recuperable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="chute récupérable (%)",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces_profile",
                        to="technique.article",
                        verbose_name="article fabriqué",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_profile",
                        to="chiffrage.devis",
                        verbose_name="devis",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pieces",
                        to="decoupe.profilesection",
                        verbose_name="section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Débit de profilé",
                "verbose_name_plural": "Débits de profilés",
                "ordering": ["pk"],
            },
        ),
    ]
