# Generated by Django 5.2.17 on 2026-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0027_sections_profiles_initiales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrecoupe",
            name="origine",
            field=models.CharField(
                choices=[
                    ("machine", "Relevées sur la machine"),
                    ("calcule", "Calculées depuis l'usinabilité (estimation)"),
                    (
                        "extrapole",
                        "Extrapolées du tableau du constructeur (estimation)",
                    ),
                ],
                default="machine",
                help_text="Jet d'eau : les vitesses « calculées » depuis l'usinabilité sont une estimation à confirmer. Laser : jamais de calcul d'usinabilité, les vitesses viennent du tableau du constructeur (« extrapolées » : épaisseur absente du tableau). Les vitesses relevées sur la machine ne sont jamais écrasées.",
                max_length=12,
                verbose_name="origine des vitesses",
            ),
        ),
    ]
