# Generated by Django 5.2.17 on 2026-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0029_laser_extrapole"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrecoupe",
            name="bord_tole_mm",
            field=models.FloatField(
                blank=True,
                help_text="Bande non découpée sur le pourtour de la tôle pour cette épaisseur. Vide : la règle du procédé s'applique (plancher des réglages de coupe ; au laser, jamais moins que l'épaisseur). Le plus grand des deux est retenu.",
                null=True,
                verbose_name="bord de tôle (mm)",
            ),
        ),
        migrations.AddField(
            model_name="reglageprocede",
            name="bord_tole_minimum_mm",
            field=models.FloatField(
                default=5,
                help_text="Plancher du bord de tôle (bande non découpée sur le pourtour), quelles que soient la matière et l'épaisseur (jet d'eau : 5 constant ; laser : 10). Au laser, le bord grandit avec l'épaisseur (jamais moins que l'épaisseur) ; le paramètre de coupe peut imposer plus.",
                verbose_name="bord de tôle minimal (mm)",
            ),
        ),
    ]
