# Generated by Django 5.2.17 on 2026-10-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0031_bord_de_tole_laser"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrecoupe",
            name="temps_mise_en_place_min",
            field=models.FloatField(
                blank=True,
                help_text="Exception à la valeur du poste de travail (ex. tôle épaisse plus longue à poser). Vide = valeur du poste.",
                null=True,
                verbose_name="mise en place d'une tôle (min)",
            ),
        ),
    ]
