# Generated by Django 5.2.17 on 2026-10-09 18:58

from django.db import migrations, models


def creer_reglage(apps, schema_editor):
    apps.get_model("decoupe", "ReglageImbrication").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ("decoupe", "0032_reglage_par_tole"),
        ("technique", "0016_reprendre_reglage_decoupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglageImbrication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seuil_chutes_pct",
                    models.FloatField(
                        default=20,
                        help_text="Taux de chutes entre pièces = (surface consommée − surface des pièces) ÷ surface consommée ; la chute de bout de la dernière tôle, récupérée, n'y compte pas. Si le meilleur format d'un niveau de priorité dépasse ce taux, le niveau suivant est calculé aussi.",
                        verbose_name="seuil de chutes entre pièces (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglage d'imbrication",
                "verbose_name_plural": "Réglage d'imbrication",
            },
        ),
        migrations.AddField(
            model_name="formattole",
            name="familles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ce format n'existe que pour ces familles (et leurs nuances). Vide et sans nuance précisée : toutes les matières.",
                related_name="formats_tole",
                to="technique.famillematiere",
                verbose_name="familles de matière",
            ),
        ),
        migrations.AddField(
            model_name="formattole",
            name="matieres",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ce format n'existe que pour ces nuances précises (en plus des familles ci-dessus).",
                related_name="formats_tole",
                to="technique.matiere",
                verbose_name="nuances de matière",
            ),
        ),
        migrations.AddField(
            model_name="formattole",
            name="priorite",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 — en stock / usuel"),
                    (2, "2 — sur commande"),
                    (3, "3 — exceptionnel"),
                ],
                default=1,
                help_text="L'imbrication calcule d'abord les formats de priorité 1 ; elle n'essaie les suivants que si le taux de chutes entre pièces dépasse le seuil des réglages d'imbrication (ou sur demande : « Calculer tous les formats »).",
                verbose_name="priorité d'utilisation",
            ),
        ),
        migrations.RunPython(creer_reglage, migrations.RunPython.noop),
    ]
