# Generated by Django 5.2.17 on 2026-08-31 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tiers",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("raison_sociale", models.CharField(max_length=200)),
                (
                    "type_tiers",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("fournisseur", "Fournisseur"),
                            ("les_deux", "Les deux"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        help_text="Obligatoire pour la facturation électronique",
                        max_length=14,
                    ),
                ),
                (
                    "numero_tva",
                    models.CharField(
                        blank=True, help_text="TVA intracommunautaire", max_length=20
                    ),
                ),
                (
                    "conditions_paiement",
                    models.CharField(
                        blank=True,
                        help_text="Valeur par défaut, reprise sur devis/commande",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiers",
                "verbose_name_plural": "Tiers",
                "ordering": ["raison_sociale"],
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_adresse",
                    models.CharField(
                        choices=[
                            ("facturation", "Facturation"),
                            ("livraison", "Livraison"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text='Ex. "Siège", "Entrepôt Nord"',
                        max_length=100,
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=20)),
                ("ville", models.CharField(max_length=100)),
                (
                    "est_principale",
                    models.BooleanField(
                        default=False, help_text="Adresse par défaut proposée"
                    ),
                ),
                (
                    "tiers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to="commercial.tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["tiers", "type_adresse"],
            },
        ),
    ]
