# Generated by Django 5.2.17 on 2026-08-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresse",
            name="adresse",
            field=models.CharField(max_length=255, verbose_name="adresse"),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="code_postal",
            field=models.CharField(max_length=20, verbose_name="code postal"),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="est_principale",
            field=models.BooleanField(
                default=False,
                help_text="Adresse par défaut proposée",
                verbose_name="adresse principale",
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="libelle",
            field=models.CharField(
                blank=True,
                help_text='Ex. "Siège", "Entrepôt Nord"',
                max_length=100,
                verbose_name="libellé",
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="tiers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresses",
                to="commercial.tiers",
                verbose_name="tiers",
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="type_adresse",
            field=models.CharField(
                choices=[("facturation", "Facturation"), ("livraison", "Livraison")],
                max_length=20,
                verbose_name="type d'adresse",
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="ville",
            field=models.CharField(max_length=100, verbose_name="ville"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="fonction",
            field=models.CharField(blank=True, max_length=100, verbose_name="fonction"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, verbose_name="prénom"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="telephone",
            field=models.CharField(blank=True, max_length=30, verbose_name="téléphone"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tiers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="commercial.tiers",
                verbose_name="tiers",
            ),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="code",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="conditions_paiement",
            field=models.CharField(
                blank=True,
                help_text="Valeur par défaut, reprise sur devis/commande",
                max_length=200,
                verbose_name="conditions de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="numero_tva",
            field=models.CharField(
                blank=True,
                help_text="TVA intracommunautaire",
                max_length=20,
                verbose_name="numéro de TVA",
            ),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="raison_sociale",
            field=models.CharField(max_length=200, verbose_name="raison sociale"),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="siret",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire pour la facturation électronique",
                max_length=14,
                verbose_name="SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="tiers",
            name="type_tiers",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("fournisseur", "Fournisseur"),
                    ("les_deux", "Les deux"),
                ],
                max_length=20,
                verbose_name="type de tiers",
            ),
        ),
    ]
