# Generated by Django 5.2.17 on 2026-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0003_alter_adresse_adresse_alter_adresse_code_postal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TauxTVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text='Ex. "Taux normal"',
                        max_length=50,
                        unique=True,
                        verbose_name="nom",
                    ),
                ),
                (
                    "taux",
                    models.FloatField(
                        help_text="Ex. 20 pour 20 %", verbose_name="taux (%)"
                    ),
                ),
                (
                    "est_defaut",
                    models.BooleanField(
                        default=False,
                        help_text="Un seul taux peut être coché par défaut ; proposé automatiquement sur les nouvelles lignes de devis.",
                        verbose_name="taux par défaut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de TVA",
                "verbose_name_plural": "Taux de TVA",
                "ordering": ["-taux"],
            },
        ),
    ]
