# Generated by Django 5.2.17 on 2026-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0005_seed_taux_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="est_principal",
            field=models.BooleanField(
                default=False,
                help_text="Contact par défaut proposé",
                verbose_name="contact principal",
            ),
        ),
    ]
