# Generated by Django 5.2.17 on 2026-09-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0006_contact_est_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="adresse_livraison",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionnel : associe ce contact à une adresse de livraison précise du tiers (ex. le contact sur place à un site). Proposé en priorité sur cette adresse, avant le contact principal du tiers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="commercial.adresse",
                verbose_name="adresse de livraison associée",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="est_principal",
            field=models.BooleanField(
                default=False,
                help_text="Contact par défaut proposé pour le tiers",
                verbose_name="contact principal",
            ),
        ),
    ]
