# Generated by Django 5.2.17 on 2026-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0007_contact_adresse_livraison_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelaiPropose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text='Ex. "2 semaines", "Sur stock"',
                        max_length=100,
                        unique=True,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre de présentation des suggestions",
                        verbose_name="ordre d'affichage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délai proposé",
                "verbose_name_plural": "Délais proposés",
                "ordering": ["ordre", "libelle"],
            },
        ),
    ]
