# Generated by Django 5.2.17 on 2026-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0008_delaipropose"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiers",
            name="regime_fiscal",
            field=models.CharField(
                choices=[
                    ("france", "France"),
                    ("france_exonere", "France (exonéré de TVA)"),
                    ("intra_ue", "Intracommunautaire (UE)"),
                    ("hors_ue", "Hors Union européenne"),
                ],
                default="france",
                help_text="Détermine, avec le poste de gestion d'un article, quel compte d'achat/vente s'applique automatiquement (comptabilite.PosteGestion).",
                max_length=20,
                verbose_name="régime fiscal",
            ),
        ),
    ]
