# Generated by Django 5.2.17 on 2026-09-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0009_tiers_regime_fiscal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text='Ex. "30 jours fin de mois", "Comptant"',
                        max_length=100,
                        unique=True,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "nombre_jours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Délai avant échéance, en jours",
                        null=True,
                        verbose_name="nombre de jours",
                    ),
                ),
                (
                    "fin_de_mois",
                    models.BooleanField(
                        default=False,
                        help_text="Échéance reportée en fin de mois",
                        verbose_name="fin de mois",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition de paiement",
                "verbose_name_plural": "Conditions de paiement",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code ISO 3166-1 alpha-2",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "est_ue",
                    models.BooleanField(
                        default=False, verbose_name="membre de l'Union européenne"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["nom"],
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="telephone",
        ),
        # RemoveField + AddField plutôt qu'un AlterField : le champ change
        # de type (CharField -> ForeignKey), Postgres ne sait pas caster
        # une valeur texte existante ("" en particulier) en identifiant
        # numérique. Les anciennes valeurs de conditions_paiement (texte
        # libre) sont donc perdues — décision assumée, voir la conversation :
        # aucune donnée de production ne dépendait encore de ce champ.
        migrations.RemoveField(
            model_name="tiers",
            name="conditions_paiement",
        ),
        migrations.AddField(
            model_name="tiers",
            name="conditions_paiement",
            field=models.ForeignKey(
                blank=True,
                help_text="Valeur par défaut, reprise sur devis/commande",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tiers",
                to="commercial.conditionpaiement",
                verbose_name="conditions de paiement",
            ),
        ),
        migrations.CreateModel(
            name="ContactTelephone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_telephone",
                    models.CharField(
                        choices=[
                            ("portable", "Portable"),
                            ("bureau", "Bureau"),
                            ("fixe", "Fixe"),
                            ("fax", "Fax"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="numéro")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telephones",
                        to="commercial.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de téléphone",
                "verbose_name_plural": "Numéros de téléphone",
                "ordering": ["contact", "type_telephone"],
            },
        ),
        migrations.AddField(
            model_name="adresse",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                help_text="Détermine automatiquement le régime fiscal du tiers si c'est l'adresse principale (livraison en priorité, sinon facturation).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adresses",
                to="commercial.pays",
                verbose_name="pays",
            ),
        ),
    ]
