# Generated by Django 5.2.17 on 2026-09-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0011_seed_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devise",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code ISO 4217",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "symbole",
                    models.CharField(
                        blank=True,
                        help_text='Ex. "€", "$", "£"',
                        max_length=5,
                        verbose_name="symbole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="tiers",
            name="bic",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="BIC / SWIFT"
            ),
        ),
        migrations.AddField(
            model_name="tiers",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="En vue d'un virement (fournisseur notamment)",
                max_length=34,
                verbose_name="IBAN",
            ),
        ),
        migrations.AddField(
            model_name="tiers",
            name="devise",
            field=models.ForeignKey(
                blank=True,
                help_text="Devise de facturation de ce tiers (un client hors UE ne facture pas forcément en euros)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tiers",
                to="commercial.devise",
                verbose_name="devise",
            ),
        ),
    ]
