# Generated by Django 5.2.17 on 2026-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0013_seed_devise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttelephone",
            name="type_telephone",
            field=models.CharField(
                choices=[
                    ("portable", "Portable"),
                    ("bureau", "Bureau"),
                    ("fixe", "Fixe"),
                    ("fax", "Fax"),
                    ("autre", "Autre"),
                ],
                default="portable",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
