# Generated by Django 5.2.17 on 2026-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0015_rename_adresse_livraison_contact_adresse_associee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttelephone",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Optionnel : pas toujours connu",
                max_length=30,
                verbose_name="numéro",
            ),
        ),
    ]
