# Generated by Django 5.2.17 on 2026-09-11 07:15, puis réécrit à la main :
# migrate.py --check aurait fait un RemoveField(type_adresse) AVANT les deux
# AddField, perdant la donnée existante avant qu'on ait pu la reporter sur
# les nouveaux champs. Réordonné en Add -> report des données -> Remove.

from django.db import migrations, models


def reporter_type_adresse(apps, schema_editor):
    Adresse = apps.get_model("commercial", "Adresse")
    Adresse.objects.filter(type_adresse="livraison").update(est_livraison=True)
    Adresse.objects.filter(type_adresse="facturation").update(est_facturation=True)


def restaurer_type_adresse(apps, schema_editor):
    # Une adresse cochée pour les deux à la fois (impossible avant cette
    # migration) retomberait arbitrairement sur "livraison" en cas de
    # migrate en arrière — c'est la seule perte d'information possible ici.
    Adresse = apps.get_model("commercial", "Adresse")
    Adresse.objects.filter(est_livraison=True).update(type_adresse="livraison")
    Adresse.objects.filter(est_livraison=False, est_facturation=True).update(type_adresse="facturation")


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0016_alter_contacttelephone_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="adresse",
            name="est_facturation",
            field=models.BooleanField(default=False, verbose_name="facturation"),
        ),
        migrations.AddField(
            model_name="adresse",
            name="est_livraison",
            field=models.BooleanField(default=False, verbose_name="livraison"),
        ),
        migrations.RunPython(reporter_type_adresse, restaurer_type_adresse),
        migrations.RemoveField(
            model_name="adresse",
            name="type_adresse",
        ),
        migrations.AlterModelOptions(
            name="adresse",
            options={
                "ordering": ["tiers", "id"],
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
    ]
