# Generated by Django 5.2.17 on 2026-10-03 10:04

import comptes.champs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0018_seed_taux_tva_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tauxtva",
            name="taux",
            field=comptes.champs.ChampDecimal(
                decimal_places=2,
                help_text="Ex. 20 pour 20 %",
                max_digits=7,
                verbose_name="taux (%)",
            ),
        ),
    ]
